test/unit/Makefile.am, test/unit/micro_unit_shmem.c
micro unit test addition for initial fabric interface development and debugging
=> test/unit: adding micro_unit_shmem.c

LICENSE, config/ompi_check_ofi.m4, config/shmem_check_type.m4, configure.ac, src/Makefile.am, src/collectives.c, src/collectives_c.c, src/init.c, src/shmem_collectives.h, src/shmem_comm.h, src/shmem_synchronization.h, src/transport_ofi.c, src/transport_ofi.h
generalization of datatypes for multi-transport usage, and OFI transport insert
=> Ofi transport

src/transport_portals4.c, src/transport_portals4.h
MDs span should not be used anymore
=> Use a single Memory Descriptor to cover all of memory

src/transport_ofi.c, src/transport_ofi.h
-require provider to track command queue resource management
-only block on cq_drain when there are events on the queue to drain
vs blocking until empty
=> OFI: cq refactor -> use RM

shmem_pmi/simple_pmi.c, src/transport_ofi.c, test/unit/Makefile.am
Cleanup of PR #60.  Adds 2c7270f, which fixes deadlock issue.
=> Global exit fix

.travis.yml
=> Add ISx to CI testing script

.travis.yml, src/collectives.c, src/init.c, src/shmem_free_list.c, src/transport_ofi.c, src/transport_ofi.h
+included added error checking to environment variable conversion
=> small memory management clean-up init/ofi

.travis.yml, configure.ac
=> Add rpath option

config/ompi_check_ofi.m4, config/sandia_check_xpmem.m4, configure.ac, src/transport_ofi.c, src/transport_ofi.h
Add support for MR_BASIC.
This patch should be reviewed by our OFI expert, @kseager, before merging.
=> OFI support for MR_BASIC

src/shmem_lock.h, test/unit/Makefile.am, test/unit/test_lock_cswap.c
Fix lock implementation bug and add a test case for cswap race that we are currently tracking.
=> Fix lock implementation bug

config/ompi_check_portals4.m4
=> Remove obsolete configure checks

test/unit/micro_unit_shmem.c
=> Fix initialization race in micro_unit_shmem test

src/Makefile.am, src/collectives.c, src/init.c, src/shmem_collectives.h, src/shmem_internal.h, src/transport_ofi.c, src/util.c
Clean up handling of environment variables and resolve several build warnings.
=> Code cleanups

test/performance/msgrate.c, test/unit/asym_alloc.c, test/unit/bcast.c, test/unit/bcast_flood.c, test/unit/big_reduction.c, test/unit/bigput.c, test/unit/fcollect64.c, test/unit/pingpong-short.c, test/unit/pingpong.c, test/unit/spam.c, test/unit/to_all.c
=> Clean up test cases

.travis.yml
=> Point UH tests back at upstream repository

test/performance/shmem_perf_suite/Makefile.am
=> perf_tests: makedist clean-up

test/performance/shmem_perf_suite/bw_common.h, test/performance/shmem_perf_suite/common.h, test/performance/shmem_perf_suite/latency_common.h
=> Clean up build warnings in perf suite

src/data_c.c, src/shmem_comm.h, src/transport.h, src/transport_ofi.c, src/transport_ofi.h, src/transport_portals4.h
1) took out long_frag usage from OFI transport
2) refactored nbi pathway in transport
3) added nbi to portals4 transport
resolves issue #91
=> 1.3 transport cleanups

src/transport_ofi.c
Add support for manual interface selection via SMA_OFI_IFACE environment
variable.  OFI transport init code was refactored (query_for_fabric was
merged into transport_init) to preserve list of fabrics, so that
fi_freeinfo can be called.
=> OFI: Add support for manual interface selection

src/transport_ofi.c
This reverts commit 29ce6ecc7ea8f243c8de1fba741bce96dea793ed, reversing
changes made to 51d8851f3f11276fc1a3e92277313ca2486aa4ba.
=> Revert "Merge pull request #159 from jdinan/topic/iface-selection-ofi"

.travis.yml, configure.ac
=> config: added --enable-av-map

src/transport_ofi.c
Please review -- @kseager and @sayantansur
=> Split AV setup into publish/populate

src/transport_ofi.c
=> OFI: init fix for FI_RMA_EVENT

src/transport_ofi.c
Relax assumptions about value of OFI datatype and atomic operation
constants.
=> OFI: Tweaks to atomic checks

src/transport_ofi.h
+only force completion of outstanding puts after a nb put
+only force completion in fragmented put case
@jdinan please review
=> OFI: improve nb bw

mpp/shmemx.h.in, src/query_c.c, test/performance/shmem_perf_suite/Makefile.am, test/performance/shmem_perf_suite/bi_dir.h, test/performance/shmem_perf_suite/bw_common.h, test/performance/shmem_perf_suite/common.h, test/performance/shmem_perf_suite/latency_common.h, test/performance/shmem_perf_suite/shmem_bibw_get_perf.c, test/performance/shmem_perf_suite/shmem_bibw_nb_get_perf.c, test/performance/shmem_perf_suite/shmem_bibw_nb_put_perf.c, test/performance/shmem_perf_suite/shmem_bibw_put_perf.c, test/performance/shmem_perf_suite/shmem_bw_get_perf.c, test/performance/shmem_perf_suite/shmem_bw_nb_get_perf.c, test/performance/shmem_perf_suite/shmem_bw_nb_put_perf.c, test/performance/shmem_perf_suite/shmem_bw_put_perf.c, test/performance/shmem_perf_suite/shmem_latency_get_perf.c, test/performance/shmem_perf_suite/shmem_latency_nb_get_perf.c, test/performance/shmem_perf_suite/shmem_latency_nb_put_perf.c, test/performance/shmem_perf_suite/shmem_latency_put_perf.c, test/performance/shmem_perf_suite/uni_dir.h, test/unit/spam.c
+enables stand-alone build for perf tests
+adds non-blocking tests
+fixes shmem_free bug that showed up in Cray SHMEM runs
@jdinan or @sayantansur for review
=> Nb perf tests

mpp/shmem.h.in, src/data_c.c, test/unit/Makefile.am, test/unit/rma_coverage.c
This commit adds the missing functions the simple way so they can be included in the upcoming release, and includes the rma_coverage test.
=> Add shmem_char_{iput,iget}

test/performance/shmem_perf_suite/Makefile.am, test/performance/shmem_perf_suite/int_element_latency.h, test/performance/shmem_perf_suite/latency_common.h, test/performance/shmem_perf_suite/round_t_latency.h, test/performance/shmem_perf_suite/shmem_latency_get_perf.c, test/performance/shmem_perf_suite/shmem_latency_nb_get_perf.c, test/performance/shmem_perf_suite/shmem_latency_nb_put_perf.c, test/performance/shmem_perf_suite/shmem_latency_put_perf.c, test/performance/shmem_perf_suite/stream_int_latency.h
small put/get streaming latency addition
@jdinan last thing we need on my end for 1.3
=> Latency perf addition

src/transport_ofi.c
=> OFI: remove ep2mr bind

.travis.yml
=> Travis: Set FI_LOG_LEVEL=warn

NEWS
=> Update NEWS for 1.3.0 release

NEWS
=> NEWS File Update

test/performance/shmem_perf_suite/int_element_latency.h, test/performance/shmem_perf_suite/round_t_latency.h, test/performance/shmem_perf_suite/shmem_latency_get_perf.c, test/performance/shmem_perf_suite/shmem_latency_nb_get_perf.c, test/performance/shmem_perf_suite/shmem_latency_nb_put_perf.c, test/performance/shmem_perf_suite/shmem_latency_put_perf.c
=> Minor cleanups to silence build warnings in perf suite

.travis.yml
=> Travis: Use libfabric v1.3.0 instead of master

.travis.yml
=> Travis: re-enable libfabric warnings

NEWS, mpp/shmem.h.in, src/data_c.c, test/unit/Makefile.am, test/unit/rma_coverage.c
Refactoring work done by @jpdoyle to macroize the OpenSHMEM header and language bindings.
=> Supermacrohappiness refactoring

README
@kseager 
Signed-off-by: Howard Pritchard <howardp@lanl.gov>
=> README: document large pages for sym heap

test/performance/tests/msgrate.c
=> Fix pwrk initialization bug is msgrate test

.travis.yml
Signed-off-by: Shantonu Hossain <shantonu.hossain@intel.com>
=> Restore the use of libfabric master instead of v1.3.0

src/transport_ofi.c, src/transport_ofi.h
@jdinan please review - I put my reasoning for each commit in the commit message
=> Atomic nb sizing

test/performance/shmem_perf_suite/Makefile.am, test/performance/shmem_perf_suite/bw_common.h, test/performance/shmem_perf_suite/common.h, test/performance/shmem_perf_suite/shmem_bibw_atomics_perf.c, test/performance/shmem_perf_suite/shmem_bw_atomics_perf.c
@jdinan @jpdoyle if someone could review...
+tested on CORI
+output attachment (for review purposes) 
+also I could squish some commits.... 
[shmem_bw_atomics_perf_sample.txt](https://github.com/Sandia-OpenSHMEM/SOS/files/452866/shmem_bw_atomics_perf_sample.txt)
=> Bw atomic perf

configure.ac, mpp/pshmem.h, mpp/shmem.h.in, src/data_c.c, test/unit/Makefile.am, test/unit/rma_coverage.c
Extend RMA coverage unit test to test the profiling interface and fix several
bugs in the profiling API.
=> Add unit test coverage for profiling interface

test/performance/shmem_perf_suite/bw_common.h
=> Fix warnings in BW perf suite

test/unit/shmem_info_f.f90
=> Bugfix to Fortran info test

src/transport_ofi.c
Closes #251 
@tonycurtis Thanks for the bug report!
=> Fix out of bounds array access

src/transport_ofi.c
Signed-off-by: James Dinan james.dinan@intel.com
=> OFI: Disable unused caps

src/symmetric_heap_c.c
Fixes for several leaks in huge page support that were identified by Coverity.
=> Fix exception handling and leaks in huge page code

src/malloc.c
=> Update dlmalloc from 2.8.4 to 2.8.6

NEWS
=> Update NEWS to log changes since v1.3.1

src/transport_ofi.c
=> OFI: Fix missing fi_wait_obj attr on cntrs

configure.ac
=> Add --enable-debug and cleanup --enable-picky

src/transport_ofi.c, src/transport_ofi.h
not applicable to RMA fixes issue #285.
=> remove fi_context usage

src/atomic_c.c4, test/performance/shmem_perf_suite/bw_common.h, test/performance/shmem_perf_suite/common.h, test/performance/shmem_perf_suite/int_element_latency.h, test/performance/shmem_perf_suite/latency_common.h, test/performance/shmem_perf_suite/round_t_latency.h, test/performance/shmem_perf_suite/shmem_latency_get_perf.c, test/performance/shmem_perf_suite/shmem_latency_put_perf.c
fixed a bug in the atomic bindings, fixed a bug in the latency IO, and enabled ease of use with SHMEM version 1.0 (IFS)
=> Perf tests

.travis.yml
=> Point travis back at main PRK repository

src/transport_ofi.c
=> Compatibility with providers that need FI_CONTEXT

.travis.yml, Makefile.am, configure.ac, test/unit/Makefile.am
=> Warning when PMI not detected

config/opal_config_pthreads.m4, configure.ac, test/unit/Makefile.am
Use pthread configury script lifed from OpenMPI.
=> Add configure test for pthreads support

src/runtime-pmi2.c
-missing header file from PR #305
-fixed bug in initialization
-removed compiler warnings
=> fixes for pmi2

.travis.yml, configure.ac, src/transport_ofi.c, src/transport_ofi.h
=> Add support for local/remote completion polling

shmem_pmi/simple_pmi.c
=> Pull error checking update to PMI from upstream

.travis.yml
What we have seems to be working, but this check should be more robust.
=> Travis: Update DISABLE_FORTRAN checks

.travis.yml
=> Travis: Add -std=c99 to PRK compiler flags

src/collectives.c
=> Fix typo in collectives code

scripts/simple-build-ofi.sh
=> Add simple SOS-OFI build script

src/transport_ofi.c
The OFI transport was requesting the maximum available mr_key_size that
OFI supports (value returned in domain_attr->mr_key_size from
fi_getinfo), when depending on compile-time options it may only need a
key size of 1 or 0.  Logic was added to request the appropriate value
depending on these compile time options.
Signed-off-by: Lisanna Dettwyler <levi.e.dettwyler@intel.com>
=> Do not request OFI mr_key_size > 0 if not needed

config/opal_check_pmi.m4
--enable_pmi2 option to use pmi2 interface with portals4
=> Enable pmi2 option with portals4

src/transport_ofi.h
=> Check if completion ptr is NULL in OFI put_nb

NEWS
=> Mention --disable-bounce-buffers in NEWS

test/performance/tests/Makefile.am, test/performance/tests/msgrate.c
Put this back for v1.3.2 while users migrate over to the new perf suite benchmarks.
=> Put back msgrate benchmark

NEWS, README
=> Update NEWS and README files

NEWS, configure.ac
=> Update version number to 1.3.2

scripts/simple-build-ofi.sh
=> Bump version in simple build script to v1.3.2

test/unit/complex_reductions_f.f90
resolves #371, assuming it passes with `gfortran`.  i tested locally against ifort 17.
=> Fix issue 371

configure.ac, test/unit/bcast.c, test/unit/bcast_flood.c, test/unit/big_reduction.c, test/unit/get_g.c, test/unit/max_reduction.c, test/unit/to_all.c
Lots of whitespace changes here.  If you refuse those, at least cherry-pick https://github.com/Sandia-OpenSHMEM/SOS/commit/0abeedcb812580cb7b4cf8d083f9d57638b7aba5.
=> Silence -Wmisleading-indentation

.travis.yml
Let's try testing icc for non-PRs only to see if the merge into master tests icc.
=> Try icc for non-PRs only

.travis.yml
I made a bash spacing mistake in #379...
=> Fix bash typo in non-PR icc attempt

.travis.yml
=> Travis: put back testing of threads build

.travis.yml, mpp/shmemx_c_func.m4, src/query_c.c, test/unit/Makefile.am, test/unit/pcontrol.c
Add function to allow application to interact with profiling tools
(c.f. MPI_Pcontrol).
=> Add shmemx_pcontrol extension

NEWS, configure.ac, src/symmetric_heap_c.c, test/unit/shmemalign.c
* Update NEWS
* Bump version to v1.3.3rc1
* Last minute fixes to memory management API
=> Updates for v1.3.3rc1 release

NEWS, configure.ac
=> Bump version number to v1.3.3

src/collectives.c
=> Fix leak in SW reduction implementation

test/unit/lfinc.c, test/unit/pingpong-short.c
* Add input validation check to lfinc
* Remove debugging short circuit from pingpong-short
=> Minor unit test fixes from Coverity scans

.travis.yml, configure.ac, src/shmem_comm.h, src/shmem_env.c
=> Add memcpy "transport"

test/apps/mandelbrot.c
=> Quiet warnings in Mandelbrot build

README
=> Update SMA_ env vars in README

NEWS, configure.ac
* Update NEWS
* Bump version number in configure.ac
=> SOS v1.3.4 release updates

NEWS, configure.ac, src/transport_ofi.c
* Merge in changes from master
* Update configure.ac and NEWS for v1.4.0a1 release
=> v1.4.0a1 Updates

configure.ac
=> Add Fortran deprecation warning

src/transport_ofi.c
=> OFI: Rename "contexts_size" -> "contexts_len"

.travis.yml, configure.ac, mpp/shmemx.h4.in, src/transport_none.h, src/transport_ofi.c, src/transport_ofi.h, src/transport_portals4.c, test/apps/gups.c
Assorted code cleanup from v1.4.0-dev review.
=> v1.4.0 cleanup

NEWS
=> Remove extext mention from NEWS

configure.ac, src/init.c
Fix LD_PRELOAD error encountered by tools folks.
=> Make data_start/end weak symbols

NEWS, configure.ac
=> v1.4.0rc2 release updates

mpp/shmemx.h4.in, src/transport_portals4.c, src/transport_portals4.h
* Add support for per-context CTs
* Make bounce buffering and blocking put isolation per-context options
=> Portals: Update contexts implementation

configure.ac, src/init.c
Cherry pick the data segment bugfix from v1.4.0 to properly support tools on the v1.3.x series.
=> Cherry pick data segment bugfix from v1.4.0

NEWS, configure.ac
- Update NEWS
- Bump version number in configure.ac
=> SOS v1.3.5 release updates

sandia-openshmem.spec.in
=> Fix manpage installation in spec file

test/performance/shmem_perf_suite/Makefile.am
Use the OpenMP CFLAGS detected by autoconf.
=> Fix OpenMP build in perf suite

scripts/simple-build-ofi.sh
=> Update SOS/libfabric ver. in simple build script

scripts/simple-build-ofi.sh
=> Allow user to set SOS/libfabric ver, update Hydra

scripts/simple-build-ofi.sh
=> Fix Hydra location in simple build script

.travis.yml
=> Travis: Get Mellanox tests from upstream repository

.travis.yml
=> Travis: Disable -Werror when building Mellanox tests

.travis.yml, configure.ac, src/init.c, src/shmem_env_defs.h
=> Fix preprocessor clash with --disable-aslr-check

src/transport_ofi.c
When I added support for multiple tid types, I forgot to update the UT_hash table to use the struct as a key instead of the int.  This led to problems when allocating OFI STX's for private contexts.
=> Use HASH_FIND/ADD, not HASH_FIND/ADD_INT for tids

test/unit/web.c
=> Use constant number of threads in web

.gitignore, configure.ac, test/include/Makefile.am, test/include/uthash.h, test/unit/Makefile.am, test/unit/mt_lock.c, test/unit/mt_lock.h, test/unit/mt_lock_test.c
=> Add multithreaded lock unit test

src/transport_ofi.c
=> Add mutex lock/unlock to ctx_destroy for STX pool

src/transport_ofi.c, src/transport_ofi.h, test/apps/gups.c, test/performance/shmem_perf_suite/bi_dir.h, test/performance/shmem_perf_suite/bw_common.h, test/performance/shmem_perf_suite/int_element_latency.h, test/performance/shmem_perf_suite/latency_common.h, test/performance/shmem_perf_suite/round_t_latency.h, test/performance/shmem_perf_suite/shmem_bibw_atomics_perf.c, test/performance/shmem_perf_suite/shmem_bw_atomics_perf.c, test/performance/shmem_perf_suite/shmem_latency_get_perf.c, test/performance/shmem_perf_suite/shmem_latency_nb_get_perf.c, test/performance/shmem_perf_suite/shmem_latency_nb_put_perf.c, test/performance/shmem_perf_suite/shmem_latency_put_perf.c, test/performance/shmem_perf_suite/target_put.h, test/performance/shmem_perf_suite/uni_dir.h, test/unit/Makefile.am, test/unit/c11_test_shmem_atomic_and.c, test/unit/c11_test_shmem_atomic_cswap.c, test/unit/c11_test_shmem_atomic_inc.c, test/unit/c11_test_shmem_atomic_or.c, test/unit/c11_test_shmem_atomic_swap.c, test/unit/c11_test_shmem_atomic_xor.c, test/unit/cxx_test_shmem_atomic_and.cpp, test/unit/cxx_test_shmem_atomic_cswap.cpp, test/unit/cxx_test_shmem_atomic_inc.cpp, test/unit/cxx_test_shmem_atomic_or.cpp, test/unit/cxx_test_shmem_atomic_swap.cpp, test/unit/cxx_test_shmem_atomic_xor.cpp, test/unit/shmem_info_f.f90
@davidozog Requesting your review of the OFI transport changes
@wrrobin Requesting your review of perf suite changes
=> Fix build warnings

test/performance/shmem_perf_suite/bw_common.h
=> Avoid passing NULL to strncmp in perf suite

test/performance/tests/msgrate.c
Call finalize before exit, remove psync addr print.
=> Cleanup msgrate test

mpp/pshmem.h4.in, mpp/shmem_c_func.h4.in
=> Fix pshmem declarations for special cases

src/init_c.c
Cherry pick 508a52e into v1.3.x branch.
=> Fix start_pes error check (v1.3.x)

test/performance/shmem_perf_suite/bw_common.h, test/performance/shmem_perf_suite/latency_common.h
=> Fix for np < 2 in BW and Latency tests in perf suite

src/transport_ofi.h
=> Incorporation of BB counters in perf counter APIs for OFI

src/shmem_atomic.h
=> Fix missing "" in __asm__

mpp/shmemx_c_func.h4.in, src/perf_counters_c.c, src/transport_none.h, src/transport_ofi.h, src/transport_portals4.h, test/shmemx/perf_counter.c
=> Removal of the context argument from shmemx_pcntr_get_completed_target

scripts/simple-build-ofi.sh
Update to use SOS v1.4.1 and OFI v1.6.1 and fix installation directory check.
=> Update simple build script

configure.ac
=> Remove ENABLE_COMPLETION_POLLING - it's not used.

test/apps/gups.c
=> Add unused GUPS parameter: number of updates/PE

.travis.yml, src/transport_ofi.c
=> Fix SHMEM_OFI_PROVIDER env var

src/transport_ofi.c
=> Removal of FI_REMOTE_READ from target counter

src/transport_ofi.c, src/transport_ofi.h
@davidozog @wrrobin Told you guys I write bugs.  😝
=> Fix incorrect BB lock in debug message

LICENSE
=> Add uthash license to LICENSE file

test/performance/shmem_perf_suite/bi_dir.h, test/performance/shmem_perf_suite/bi_dir_ctx.h, test/performance/shmem_perf_suite/bw_common.h, test/performance/shmem_perf_suite/common.h, test/performance/shmem_perf_suite/int_element_latency.h, test/performance/shmem_perf_suite/latency_common.h, test/performance/shmem_perf_suite/latency_ctx.h, test/performance/shmem_perf_suite/round_t_latency.h, test/performance/shmem_perf_suite/shmem_bibw_atomics_perf.c, test/performance/shmem_perf_suite/shmem_bibw_get_perf.c, test/performance/shmem_perf_suite/shmem_bibw_put_ctx_perf.c, test/performance/shmem_perf_suite/shmem_bibw_put_perf.c, test/performance/shmem_perf_suite/shmem_bw_atomics_perf.c, test/performance/shmem_perf_suite/shmem_bw_get_perf.c, test/performance/shmem_perf_suite/shmem_bw_put_ctx_perf.c, test/performance/shmem_perf_suite/shmem_bw_put_perf.c, test/performance/shmem_perf_suite/shmem_latency_get_ctx_perf.c, test/performance/shmem_perf_suite/shmem_latency_get_perf.c, test/performance/shmem_perf_suite/shmem_latency_put_ctx_perf.c, test/performance/shmem_perf_suite/shmem_latency_put_perf.c, test/performance/shmem_perf_suite/target_put.h, test/performance/shmem_perf_suite/uni_dir.h, test/performance/shmem_perf_suite/uni_dir_ctx.h
=> Removal of passing perf_metrics_t struct by value in the perf suite tests

configure.ac
* Clean up help messages
* Disable bounce buffering by default
=> Configury: clean up help messages

NEWS, configure.ac
=> SOS v1.4.2 release updates

configure.ac, src/Makefile.am
=> Add explicity USE_PMI1 support (for Slurm PMI)

configure.ac, src/Makefile.am
=> Configury Updates

test/unit/Makefile.am
=> Classify CXX generic tests as shmemx tests

config/opal_check_pmi.m4
Quick fix: provide paragraph for PMIx v4.x
Signed-off-by: Ralph H Castain <rhc@open-mpi.org>
=> Fix opal_check_pmi.m4 for newer PMIx

src/transport_ofi.h
=> Fix for flags in fi_writemsg APIs

.travis.yml
=> Re-enable mellanox basic:static test w/recent fix

src/data_c.c4
=> Bugfix: Added fence for blocking put-signal

src/backtrace.c, src/symmetric_heap_c.c, src/synchronization_c.c4
@wrrobin and @davidozog Please review
=> Fix a few type-related warnings

src/synchronization_c.c4
=> Do transport probe in wait/test if condition not met

.travis.yml, configure.ac, src/transport_ofi.c, src/transport_ofi.h
=> FI_FENCE as user option

.travis.yml
Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>
=> travis: build hwloc in $TRAVIS_SRC

NEWS
=> Update NEWS file for 1.4.3rc1

test/performance/shmem_perf_suite/Makefile.am, test/performance/shmem_perf_suite/bw_common.h, test/performance/shmem_perf_suite/common.h, test/performance/shmem_perf_suite/shmem_bibw_atomics_perf.c, test/performance/shmem_perf_suite/shmem_bibw_nb_atomics_perf.c, test/performance/shmem_perf_suite/shmem_bw_atomics_perf.c, test/performance/shmem_perf_suite/shmem_bw_nb_atomics_perf.c
=> Performance tests for NB AMO

NEWS, configure.ac
=> SOS v1.4.3 release updates

configure.ac
=> Configury: Remove pmix experimental warning

test/performance/shmem_perf_suite/bi_dir_ctx.h, test/performance/shmem_perf_suite/latency_ctx.h, test/performance/shmem_perf_suite/uni_dir_ctx.h
=> Exit with 0 for context creation failure in perf tests

test/shmemx/atomic_nbi.c
Coverity is back online.  Good news is that this is the only defect worth fixing in SOS v1.4.3.  ✋
=> Fix error output in atomic NBI test

src/transport_ofi.c
Thanks to @a-ilango for the fix.
=> OFI: Request STX when querying for fabric

.travis.yml
Yay!!  --- https://blog.travis-ci.com/2018-11-08-xenial-release
=> Travis: Update to xenial

.travis.yml
=> Travis: Enable PMIx and Portals 4, both with libev

.travis.yml
=> Travis: Disable icc testing until fixed

test/apps/mandelbrot.c
=> Fix contexts args to Mandelbrot

.travis.yml
Bit of a hack, but this should catch it if we are missing any pshmem functions in the future.
=> Travis: check for missing pshmem symbols

NEWS, README
=> Updates to v1.4.4 release notes

.travis.yml, config/sandia_check_xpmem.m4
Fix a typo in the XPMEM library path check
=> Fix xpmem library path check

src/shmem_atomic.h
=> Fix incorrect type in spinlock

src/shmem_synchronization.h, src/shr_transport.h4
Addon to #922 to relax the memory model from sequential consistency to acquire/release.
=> Relax shr atomics memory model

.travis.yml
=> Updating PMIx configury in Travis

scripts/simple-build-ofi.sh
Doing the final steps in the SOS release checklist (for `tests-sos` CI).
=> Update SOS and libfabric versions in build-script

src/atomic_c.c4, src/atomic_nbi_c.c4, src/contexts_c.c, src/data_c.c4, src/shmem_internal.h
=> SHMEM_CTX_INVALID for RMA, AMO, and context creation operations

test/performance/shmem_perf_suite/bw_common.h, test/performance/shmem_perf_suite/latency_common.h, test/unit/query_thread.c
Incorporating from tests-sos PR:  https://github.com/openshmem-org/tests-sos/pull/15
=> Allow higher shmem_init thread levels in tests

sandia-openshmem.spec.in
=> Removing debug package in RPM build

src/shmem_comm.h, src/transport_ucx.h
=> Fix completion logic bug

.travis.yml
=> Travis UCX Update

.travis.yml
=> Travis: Update path to XPMEM kernel module

test/performance/shmem_perf_suite/README, test/performance/shmem_perf_suite/bw_common.h, test/performance/shmem_perf_suite/common.h
This feature is courtesy of @minsii.  PR #17 in tests-sos has more info:
https://github.com/openshmem-org/tests-sos/pull/17
After reviewing and merging this into master, I'll then include it in the v1.4.x branch as well (in PR #987).
=> shmem_perf_suite: add multiplier for trials value

NEWS, configure.ac
=> Version and NEWS for 1.5.0 release

.github/workflows/ci.yml
GitHub Actions testing. Tests pass.
After this is merged, future PR's and merges will be tested.
=> add github actions CI

test/spec-example/shmem_team_split_2D.c
=> Fix compiler warning in team_split_2d spec-example

test/unit/waituntil.c
Fix for https://github.com/openshmem-org/tests-sos/issues/22
=> Fix test/unit/waituntil.c PUT ordering issue with fence

test/performance/tests/shmemlatency.c
=> Rename signal to sig in shmemlatency.c for Mac/BSD

test/unit/alltoall.c, test/unit/alltoalls.c
This should fix issue #1035 
@kholland-intel - can you please check this resolves the failure you saw in these tests?
=> Fix alltoall(s) tests to use unit stride w/ teams

src/transport_portals4.c
Signed-off-by: Md Rahman <md.rahman@intel.com>
=> Resolved bug raised by issue#1052

test/performance/shmem_perf_suite/round_t_latency.h
Signed-off-by: Md Rahman <md.rahman@intel.com>
=> Replaced put with set for round trip latency tests

src/shmem_internal.h
Invoked RAISE_ERROR_* functions from SHMEM_ERR_CHECK_* macros so that the
function, filename, and line numbers are printed.
=> Updated error checking macros

LICENSE
Adding BSD-compliant license. 
@davidozog Let me know if this wording is adequate for inclusion, please send me an email otherwise, thanks!
Signed-off-by: tmh97 <thomas.huber@cornelisnetworks.com>
=> New entry in License file for Cornelis Networks

test/unit/Makefile.am, test/unit/shmem_ctx_get_team.c
@davidozog Had this unit test for a different reason, but thought it might be useful anyway. Could you please check if I missed any other condition to check for this routine?
=> Unit test for shmem_ctx_get_team

src/shmem_internal.h, src/shmem_team.c, test/unit/Makefile.am, test/unit/shmem_team_negative_stride.c
=> Teams: support negative strides, adds a unit test

src/transport_ofi.h
This address a performance issue with fetching AMOs when using the cxi provider.  It is intended to be a temporary patch until FI_DELIVERY_COMPLETE is supported with FI_MR_ENDPOINT on cxi.
=> OFI/CXI: If MR_ENDPOINT, do nbi AMOs (performance)

NEWS, configure.ac
Updated NEWS file with the few changes since v1.5.2rc1
=> NEWS: added updates for v1.5.2 release

src/uthash.h
This PR updates **uthash.h** from v2.0.1 to v2.3.0
=> src: Update uthash.h to v2.3.0

.github/workflows/ci.yml, Makefile.am, configure.ac, sandia-openshmem.spec.in
=> Optional Manpages

src/shmem_comm.h, src/transport_ofi.h
This is another temporary workaround related to PR #1134.
=> OFI/CXI: add intermittent quiet for CXI workaround

NEWS, configure.ac
This adds an entry to the `NEWS` file summarizing new features and changes for SOS v1.5.3 release candidate 1.
=> NEWS: Summarize v1.5.3 release candidate 1 updates

src/shmem_team.c
=> teams: catch team wraparound w/ negative strides
