LICENSE
config/ompi_check_ofi.m4
config/orte_check_pmi.m4
configure.ac
shmem_pmi/Makefile.am
shmem_pmi/autogen.sh
shmem_pmi/configure.ac
shmem_pmi/include/pmi.h
shmem_pmi/pmi.h
shmem_pmi/simple_pmi.c
shmem_pmi/simple_pmiutil.c
shmem_pmi/simple_pmiutil.h

++built-in pmi support
Note on usage:
build and install shmem_pmi before building shmem
to use during shmem configuration add: --with-pmi=${PWD} --with-pmi-libdir=shmem_pmi
->the above will find your libshmem_pmi.so regardless of shmem_pmi's config prefix
choosing shmem_pmi will assume mpiexec.hydra for make check (set env variables accordingly)
++if "with-ofi" isn't on configure line ofi will not be built

NEW feature: shmem_pmi

---

Makefile.am
autogen.sh
config/orte_check_pmi.m4
configure.ac
shmem_pmi/Makefile.am
src/Makefile.am

New use case model for using shmem_pmi
-thanks Jim for the idea of adding the --enable-pmi-simple feature
-reinvisioned build implementation (removed old implementation)
-if you use configure option shmem_pmi will be built in by default
else you must use the old usage pattern for pmi support
note: added autogen.sh for ease of use
This closes #23

shmem_pmi implementation update: --enable-pmi-simple

---

src/transport_ofi.c
src/transport_ofi.h

ofi_init: use inits expected error handling (return the error vs. abort on spot)
-unify usage of OFI_ABORT and check if address exists before fi_close
ofi_comm: fixed some indentation, add OFI error translation to error handling output

OFI: error handling clean-up

---

.travis.yml
README
src/transport_ofi.c

* Populate build matrix with env vars
* I contributed bugfixes to PRK, which allows us to re-enable those tests
* Remove assertion from OFI to enable disabling of bounce buffers

Updates to improve coverage of CI tests

---

src/symmetric_heap_c.c

Error checks expect NULL when symmetric heap setup fails.  Return NULL
```((void*) 0)``` instead of MAP_FAILED ```((void*) -1)``` when mmap setup method
fails.

Fix error handling in mmap symmetric heap setup

---

test/unit/Makefile.am
test/unit/asym_alloc.c

Backward compatibility test to check that the OpenSHMEM 1.1 asymmetric
memory allocation semantic works properly.

Add test for asymmetric allocation

---

autogen.sh
shmem_pmi/autogen.sh

see
http://stackoverflow.com/questions/15448582/installed-libtool-but-libtoolize-not-found
for a description of the problem.
fixes issue #86.

use glibtoolize on Mac

---

.travis.yml

Upstream dropped -lshmem from the default LIBS, rendering this
workaround unnecessary.

Drop LIBS setting workaround in PRK build

---

src/shmem_launcher_script.in

...because Intel MPI provides MPD-based mpiexec.
Intel MPI uses gawdawful MPD by default for mpiexec.  On machines where mpiexec is in the path, this leads to very sad pandas, because all the tests fail.

look for mpirun before mpiexec

---

src/collectives.c

SHMEM barrier should not return until all PEs have performed a quiet.
Move quiet call in dissemination barrier to before the barrier, rather
than after.

Fix dissemination barrier race, quiet first

---

src/accessibility_c.c
src/atomic_c.c
src/cache_management_c.c
src/collectives_c.c
src/data_c.c
src/init_c.c
src/lock_c.c
src/query_c.c
src/remote_pointer_c.c
src/symmetric_heap_c.c
src/synchronization_c.c

Include pshmem.h where needed and add missing weak symbols.

Fix errors in the profiling interface

---

src/transport_ofi.c
src/transport_ofi.h

+if provider enables a larger inject threshold use it
+assert that put_small is staying within inject boundaries
closes #72

OFI: inject usage modification

---

src/transport_ofi.h

Renamed to shmem_transport_ofi_get_mr to avoid giving the impression
that this function is part of libfabric.
Closes #130.

Rename internal fi_get_mr function

---

.travis.yml

This update removes the use of sudo, allowing Travis to run CI testing in the container environment which speeds up the turn-around time.

Update Travis to use container environment

---

src/init.c

Fix handling of calls to finalize when the library is uninitialized or
already finalized.

Fix handling of erroneous finalize calls

---

test/performance/shmem_perf_suite/latency_common.h

removing portability issue in latency output header
@hppritcha could you quickly verify this works for you?

shmem_perf_suite/latency: small output fix

---

src/transport_ofi.c

Since sandia-shmem over ofi by defalt tries to
use remote counters, it needs to request FI_RMA_EVENT
caps.  According to the libfabric man pages, this secondary
capability is required in order for the app to be able to
rely on remote counters being supported by the provider.
there was also some white space cleanup here.
unfortunately it looks like some folks use tabs, others use spaces.
@jdinan 
Signed-off-by: Howard Pritchard <howardp@lanl.gov>

request FI_RMA_EVENT in caps

---

.travis.yml

UH C tests have been updated to use the testing harness.  Update Travis success check to match.

Travis: Update success check for UH C tests

---

config/opal_check_pmi.m4
configure.ac
src/Makefile.am
src/runtime-pmi2.c

This commit adds support for using pmi2 and hence
the ability to use the Cray PMI.  Cray PMI is weird in
several ways:
1) the PMI_KVX functions only work when craypich is launched
using hydra (only supported on single node)
2) Cray has PMI2 but doesn't install a libpmi2
3) Cray has PMI2 but doesn't define PMI2_SUCCESS.
Verified using a modified ofi-transport.c that some of the
perf test work using socket provider on cray.
More work is need to the ofi layer to get the GNI provider
to work with sandia shmem.
@kseager 
@jdinan 
Signed-off-by: Howard Pritchard <howardp@lanl.gov>

pmi: add support for pmi2

---

src/transport_ofi.c

Drop a statement that had no effect and was invalid because it accessed
a pointer after the corresponding object was freed.

Drop fabric info update after free

---

README
configure.ac
src/transport_ofi.c

* Adds support for SMA_OFI_FABRIC env var to allow users to specify the fabric name (```fabric_attr->name```).  Shell-style wildcards can be used (e.g. SMA_OFI_FABRIC="en*").
* Removes support for the SMA_OFI_SERVICE env var, which is not anticipated to be useful for configuring the fabric with SHMEM.
This change is leading libfabric by a bit, but I think it's stable enough to merge.  In the future, I anticipate also adding a similar SMA_OFI_DOMAIN option to allow users to also specify the desired fabric domain.

Clean up and extend fabric selection code

---

configure.ac
src/collectives.c

The recursive doubling collectives used atomic sum on signed byte in
their psync updates.  This added a dependence on the transport layer
supporting atomic sum on byte, which caused a portability issue for the
GNI provider.
This update replaces signed byte with signed int, which results in a
larger psync; however, it still fits in a cache line on systems with
32-bit integers.

Update recdbl psync atomic to use SUM/INT

---

configure.ac
src/shmem_synchronization.h
src/transport.h
src/transport_ofi.c
src/transport_ofi.h
src/transport_portals4.c
src/transport_portals4.h

Add received counter get/wait API to the transport interface and push
Portal 4 and OFI calls in the wait implementation down into the
transport layer.

Add received counter to transport interface

---

README
src/collectives_c.c
src/init.c
src/transport_ofi.c

+environment variable option for enabling atomic limitation warnings vs. errors
+small clean-up of atomic valid output message
+initial atomic size check uses FI_SUM instead of FI_MAX since sum is more portable

OFI: added SMA_OFI_ATOMIC_CHECKS_WARN

---

configure.ac
src/transport_ofi.c

+added optional hostname exchange
+can be utilized by XPMEM for shared memory topology detection
resolves issue #164

OFI: enable USE_ON_NODE_COMMS

---

src/transport_ofi.c
src/transport_ofi.h

+OFI requirement
+additionally using cq for cntr error handling
@sayantansur : we've already discussed, but if you could review and merge in, thanks! 
@hppritcha this looks like its fixes the unit test failures we were seeing

OFI: add error cq to cntr_ep

---

src/transport_ofi.c
src/transport_ofi.h

now we detect on the fly if we need to provide reduction software support, for all other atomic limitation cases there will be a detection in init and this will cause an abort unless the atomic warn environment variable is used
@jdinan I tweaked the support from what we discussed on the phone so please review...
-I tried testing this via faking a limitation in sockets (since CORI is down)

atomic limitation support change

---

src/transport_ofi.c

-prefix to avoid potential redef

OFI: enum renaming

---

mpp/shmem.h.in
src/data_c.c
test/unit/Makefile.am
test/unit/rma_coverage.c

There is a lot of duplicated code in `shmem.h` and `data_c.c`, in which the only change between each version is the type each function operates on. This is hard to change and error prone (for example, #203 -- `shmem_char_iput` and `shmem_char_iget` are not declared or implemented). This pull request adds a few utility macros for the typeclasses in the OpenSHMEM 1.3 Spec. For example, to declare the function
void shmem_<TYPENAME>_p(<TYPE> *addr, <TYPE> value, int pe);
where \<TYPE\> is allowed to be any RMA type, as specified in 8.3.2, we currently have:
void shmem_float_p(float *addr, float value, int pe);
void shmem_double_p(double *addr, double value, int pe);
void shmem_longdouble_p(long double *addr, long double value, int pe);
void shmem_char_p(char *addr, char value, int pe);
void …

Macro-ize types, add coverage for all non-atomic RMA operations

---

src/init.c
src/shmem_comm.h
src/shmem_internal.h
src/symmetric_heap_c.c
src/transport_ofi.c

With this commit, support is added to to SOS
for allowing the symmetric heap to be backed by
large pages on Linux.
This feature is not reliant on THP feature in Linux.
The use of default large page size (2MB) is triggered
by setting the
SMA_SYMMETRIC_HEAP_USE_HUGE_PAGES
environment variable.
For systems that support multiple large pages (such
as the synthetic large pages available on Cray systems),
there is an additional env. variable
SMA_SYMMETRIC_HEAP_PAGE_SIZE
It is aware of MB, GB, etc. syntax.  So, to use the
128MB large pages on Cray system the env. variable
would be set as
export SMA_SYMMETRIC_HEAP_PAGE_SIZE=128MB
@jdinan 
@kseager 
Signed-off-by: Howard Pritchard <howardp@lanl.gov>

add support for large page sheap for linux

---

src/transport_ofi.h

Remove unused externs from OFI xport header

---

README
src/init.c
src/shmem_internal.h

Added support for SMA_DEBUG environment variable & shmem_internal_debug
variable.  Also added change to README.
Closes #41
Signed-off-by: Richard North III <richard.north.iii@intel.com>

Add support for SMA_DEBUG env var

---

src/transport_ofi.c

These attribute changes have no effect, thus they should be dropped.

OFI: Drop attr changes in cntr EP creation

---

src/transport_ofi.c
src/transport_ofi.h

If built with --enable-threads, this adds a global mutex to the OFI transport, which is locked on quiets, fences, and RMA/atomic operations.

Basic thread safety for OFI transport

---

src/util.c

Quiets build warnings, "ignoring return value of ‘asprintf’, declared
with attribute warn_unused_result", and is generally a good idea.

Check return code from asprintf

---

src/init.c

Necessary for compliance with OpenSHMEM v1.3 spec.

Add barrier to atexit handler

---

test/performance/shmem_perf_suite/bw_common.h
test/performance/shmem_perf_suite/common.h
test/performance/shmem_perf_suite/latency_common.h

The C preprocessor doesn't allow "." characters in macro names.  Rename
VERSION_1.0 macro to VERSION_1_0.

Clean up build warnings in perf suite

---

.travis.yml
Makefile.am
configure.ac
test/unit/Makefile.am

* Set default Fortran build to provide the short header (de facto standard behavior)
* Simplify PMI configury

Build system updates

---

README
config/ax_gcc_builtin.m4
configure.ac
src/init.c
src/runtime-pmi.c
src/runtime-pmi2.c
src/shmem_internal.h

Define SHMEM_TRAP_ON_ABORT and the abort routine will call the
__builtin_trap() GCC intrinsic.  Useful for generating core files and
interfacing with debuggers.

Add support for trap-on-abort

---

configure.ac

Doesn't seem to be necessary to force -std=c99.

Remove AC_PROG_CC_C99 from configure

---

configure.ac
src/Makefile.am
src/shmem_compiler_script.in

Addresses #309 & #310 by compile-checking for gnu11/gnu99 support and setting -std in CFLAGS instead of CC.

Use -std=gnu11 when available, gnu99 otherwise

---

src/symmetric_heap_c.c
src/symmetric_heap_f.c

Moving the exit barrier call in shmem_free to the entry eliminates a nasty race condition.  Similarly, shmem_realloc needs a barrier at entry.

Move/add barriers in shmem_free and shmem_realloc

---

src/shmem_internal.h
src/transport_ofi.c

Example output:
```
$ SHMEM_DEBUG=1 mpiexec -np 4 test/unit/hello
[002] DEBUG: ../../src/transport_ofi.c:1058:
[002]        OFI provider: sockets, fabric: 127.0.0.0/8, domain: lo0
[000] DEBUG: ../../src/transport_ofi.c:1058:
[000]        OFI provider: sockets, fabric: 127.0.0.0/8, domain: lo0
[001] DEBUG: ../../src/transport_ofi.c:1058:
[001]        OFI provider: sockets, fabric: 127.0.0.0/8, domain: lo0
[003] DEBUG: ../../src/transport_ofi.c:1058:
[003]        OFI provider: sockets, fabric: 127.0.0.0/8, domain: lo0
Hello World from 0 of 4
Hello World from 1 of 4
Hello World from 2 of 4
Hello World from 3 of 4
```

Improve debugging messages for OFI

---

src/symmetric_heap_c.c
test/unit/shmalloc.c

Example output:
```
$ SHMEM_SYMMETRIC_SIZE=1 mpiexec -np 2 test/unit/shmalloc
[000] WARNING: Out of symmetric memory, heap size 1048577, overrun 32768
[000]          Try increasing SHMEM_SYMMETRIC_SIZE
[000] WARNING: Out of symmetric memory, heap size 1048577, overrun 528384
[000]          Try increasing SHMEM_SYMMETRIC_SIZE
[001] WARNING: Out of symmetric memory, heap size 1048577, overrun 32768
[001]          Try increasing SHMEM_SYMMETRIC_SIZE
[001] WARNING: Out of symmetric memory, heap size 1048577, overrun 528384
[001]          Try increasing SHMEM_SYMMETRIC_SIZE
Failed source memory allocation: Cannot allocate memory
Failed source memory allocation: Cannot allocate memory
```
Closes #104

Improve out of memory error message

---

.travis.yml
scripts/cray_tests.sh
src/symmetric_heap_c.c

- The script in `scripts/cray-tests.sh` can be run independently or as a part of Travis CI.  
- Most tests currently pass, but a couple don't, presumably because of bugs in the "tree" and "recursive doubling" reduction algorithms.  It seems like they might be with weird edge cases, for example, `shmem_int_and_to_all` when `PE_Size` is 1.
- Note the NULL pointer check when `--enable-error-checking` is set, which is required for a few Cray tests to pass, because they call `shmem_free(NULL)`.
- In Travis, this commit currently clones my [openshmem branch](https://github.com/davidozog/tests-cray/tree/openshmem) of [tests-cray](https://github.com/openshmem-org/tests-cray), but I'll submit a pull request there as well.

Add Cray test suite to Travis

---

.travis.yml
config/ompi_check_ofi.m4
config/opal_check_libfabric.m4
config/opal_check_libnl.m4
config/opal_check_package.m4
config/opal_check_pmi.m4
config/opal_check_withdir.m4
config/opal_functions.m4
config/opal_setup_wrappers.m4
config/opal_summary.m4
configure.ac

This PR would update the SOS build setup to use the upstream (OMPI) check for libfabric, while still supporting the `--with-ofi` flag.  It also updates to some other upstream OPAL m4 scripts, such as check_package, check_withdir, and a setup wrapper.  This wrapper does a good job of addressing Issue #138, by explicitly setting rpath to include all external library directories.  The SOS configure then passes that rpath string to oshcc and friends via LDFLAGS.

Upstream OPAL update

---

test/performance/shmem_perf_suite/bw_common.h
test/performance/shmem_perf_suite/uni_dir.h

-only bw tests (bibw will still abort if not even PE set)
-verified change on atomic/get/put bw tests

perf tests: enable 1 PE on bw tests

---

.travis.yml

Updates the Cray tests suite in Travis to use the openshmem-org repository here:
https://github.com/openshmem-org/tests-cray

Update tests-cray github link in Travis

---

src/Makefile.am
src/init.c
src/transport_ofi.c
src/transport_portals4.c

Add the following to the SHMEM_DEBUG output:
```
Sandia OpenSHMEM 1.3.1
Build information:
Git Version             v1.3.1-177-gd2f74b6d (pr/debug-msg)
Configure Args          '--prefix=/Users/dinanjam/opt/sandia-openshmem' '--with-ofi=/Users/dinanjam/opt/libfabric' '--enable-pmi-simple' '--enable-picky' '--enable-debug' '--enable-error-checking'
Build Date              Fri Feb 24 10:38:24 EST 2017
Build CC                gcc
Build CFLAGS            -std=gnu11 -g -O2 -Wall -Wno-long-long -Wmissing-prototypes -Wstrict-prototypes -Wcomment -pedantic -g
```
Also cleans up the SHMEM_INFO output to better include on-node comms info.  Here's the full output from the hello test when both SHMEM_INFO and SHMEM_DEBUG are enabled:
```
$ SMA_INFO=1 SMA_DEBUG=1 test/unit/hello
[000] DEBUG: …
```

Add build information to debug output

---

src/collectives.c
test/unit/Makefile.am
test/unit/broadcast_active_set.c
test/unit/reduce_active_set.c
test/unit/repeated_barriers.c

This fixes several bugs, but seems to have also caused a bug in the Cray ```shmem_broadcast_all.c``` test to fail nearly every time.

Fix bugs in tree-based bcast and barrier

---

test/apps/gups.c

The verification phase repeats the GUPS experiment with each update performed while holding a mutex.  This part is really slow...

Reduce default table size in GUPS

---

src/init.c
src/transport_ofi.c
src/transport_ofi.h

Improvements to performance of thread safety prototype.
Updated default to FI_THREAD_DOMAIN, which should also improve overall performance.

Improvements to thread safety

---

src/Makefile.am

The line break I removed was causing a lot of whitespace to show up in the SHMEM_DEBUG output.

Fix gratuitous whitespace in git version output

---

src/collectives.c
src/data_f.c4
src/transport_ofi.h
src/transport_portals4.h

The transport_put_nb code assumes you want to bounce buffer, since it
was intended to support blocking put.  For a truly nonblocking put, we
should have been calling transport_put_nbi.  Since we were calling
put_nb, we have been unnecessarily bounce buffering in collect and
all-to-all collectives, which was causing some performance loss.

Use put_nbi when not requesting completion handle

---

.travis.yml
scripts/install-icc.sh

Using the technique described at github.com/nemequ/icc-travis, add icc
to the Travis build script.  This adds the install-icc.sh file to the
'scripts' directory, and an encrypted environment variable for an Intel
Parallel Studio XE 2016 serial number.

Add icc compiler to the Travis CI build matrix

---

.travis.yml

Because encrypted variables are not available to forks, only test the
icc compiler when TRAVIS_REPO_SLUG matches the upstream
value, 'Sandia-OpenSHMEM/SOS', otherwise exit with a "pass".
Note that we could also default to a "fail" for icc on forks.  But my (slight) preference is to assume it passes, then make sure the icc tests pass in Travis after we merge a PR into 'Sandia-OpenSHMEM/SOS'.  The encrypted variables shouldn't be a problem for that merge commit.

Only run icc in Travis CI if not from a Git fork

---

config/c_weak_symbols.m4
configure.ac

Check for weak symbols support when enabling the profiling interface.

Configury: Add weak symbols check

---

src/transport_ofi.c
src/transport_ofi.h

Here are all of the non-whitespace changes (gif diff -b master..):
```
diff --git a/src/transport_ofi.c b/src/transport_ofi.c
index e566866b..ac88e31a 100644
--- a/src/transport_ofi.c
+++ b/src/transport_ofi.c
@@ -236,7 +236,7 @@ static int REDUCE_ARITH_OPS[]=
};
/* Internal to SHMEM implementation atomic requirement */
-/*Locking implementation requirement */
+/* Locking implementation requirement */
#define SIZEOF_INTERNAL_REQ_DT 1
static int DT_INTERNAL_REQ[]=
{
@@ -257,30 +257,30 @@ typedef enum{
shmem_free_list_t *shmem_transport_ofi_bounce_buffers = NULL;
-//size of CQ
-const static size_t shmem_transport_ofi_queue_slots = 32768;//default CQ Depth....
+/* default CQ depth */
+const static size_t shmem_transport_ofi_queue_slots = 32768;
uint64_t shmem_transport_ofi_max_poll = …
```

Whitespace update to OFI transport

---

test/apps/gups.c
test/unit/bcast.c

OpenSHMEM requires that any asymmetric allocation must be the last call to ```shmem_malloc```.  Since the Table allocation in GUPS can be asymmetric (as reported in #384), ensure it's the last symmetric allocation call.
Closes #384

Fix asymmetric allocation bug in GUPS

---

src/symmetric_heap_c.c

Signed-off-by: Richard North III <richard.north.iii@intel.com>

Improve error message when symmetric heap setup fails

---

test/performance/shmem_perf_suite/Makefile.am
test/performance/shmem_perf_suite/bw_common.h
test/performance/shmem_perf_suite/shmem_bw_atomics_perf.c
test/performance/shmem_perf_suite/shmem_bw_get_perf.c
test/performance/shmem_perf_suite/shmem_bw_nb_get_perf.c
test/performance/shmem_perf_suite/shmem_bw_nb_put_perf.c
test/performance/shmem_perf_suite/shmem_bw_put_perf.c
test/performance/shmem_perf_suite/target_put.h
test/performance/shmem_perf_suite/uni_dir.h

This test suite adds the following input variables: -t, -l, -r
-t:  enables timing of the target side of a transfer (will output initiator timing as well, side-by-side)
-l: PEs stream across two nodes for this suite, the "left side" is the initiator side, you can reduce the PEs streaming on this side, X <= PPN 
-r: same ideas as above: "right side" is the target side of the transfer stream, you can reduce the PEs streaming on this side, X <= PPN 
feature notes: 
-only for sizes 8bytes and 4KB
-you cannot use -l/r together, if you want less on both sides, you should launch less
-window size is set at 1 and cannot be altered for -t 
Review notes:
target_put.h is best read on its own at head commit (was overhauled since initial commit)
@jdinan please review

uni-dir perf suite addition: target put/get with variable PE sets

---

src/collectives_c.c4
src/data_c.c4

Don't check args for less-than-zero errors when the type of the args is unsigned (e.g. ```size_t```).
Fixes coverity issues 169688-169781.

Remove less-than-zero arg checks for unsigned args

---

src/shmem_compiler_script.in
src/shmem_launcher_script.in

$ oshcc -h
== OSHRUN HELP ======================================
OSHRUN_LAUNCHER= gcc
== LAUNCHER HELP ====================================
Usage: gcc [options] file...
Options:
-pass-exit-codes         Exit with highest error code from a phase
--help                   Display this information
--target-help            Display target specific command line options
--help={common|optimizers|params|target|warnings|[^]{joined|separate|undocumented}}[,...]
Display specific types of command line options
(Use '-v --help' to display command line options of sub-processes)
--version                Display compiler version information
-dumpspecs               Display all of the built in spec strings
-dumpversion             Display the version of the compiler
-dumpmachine             Display the …

Updated wrappers to catch -h and --help

---

src/symmetric_heap_c.c
test/unit/shmemalign.c

The Mellanox and Cray tests have divergent requirements, defaulting to Cray.
- Mellanox expects failure for alignments of 0 and 3
- Cray expects 3 to round up to a valid alignment

Back out shmem_align changes

---

src/Makefile.am

Ensure that transport_none.h is included in the distribution tarball.

Include transport_none in sources

---

test/unit/mt_a2a.c

File was missing a pthread barrier and was causing unspecified execution.
Signed-off-by: = <=alex@mckpals.com>

Changed mt_a2a.c such that the test works.

---

.travis.yml

Move the SMA_SYMMETRIC_SIZE env var adjustment to an oshrun argument to avoid changing the environment variable setting (which may be set elsewhere in the future and would be used by all other tests).

Update SMA_SYMMETRIC_SIZE for ISx

---

test/unit/ipgm.c
test/unit/shrealloc.c

These tests are invalid when run with 1 PE, so require 2 or more PE's.  Also change exit() to shmem_global_exit() where necessary and address a small initialization issue.

Fixes shrealloc and ipgm test errors with 1 PE

---

Makefile.am
sandia-openshmem.spec.in

Adds the man pages directory to EXTRA_DIST so that "make dist" includes
them in the packages tarball.  Also adds the manpage files to the
"devel" RPM build and "oshrun" to the standard RPM.

Fix missing manpages from RPM build

---

src/shmem_comm.h
test/unit/Makefile.am
test/unit/zero_comm.c

Note that atomics are always length 1, so I added asserts to the corresponding ```atomic/put_small``` routines rather than a length check (the assertions are only included in error checking builds).

Fix handling of zero-length put/get operations

---

test/apps/gups.c

Avoid touching HPCC_PELock until after checking whether it's NULL.

Fix allocation check in GUPS

---

test/unit/asym_alloc.c
test/unit/bcast_flood.c
test/unit/put_nbi.c

Check that pointers returned by shmem_malloc/malloc are not null before dereferencing them.

Check for null pointers in unit tests

---

test/performance/shmem_perf_suite/target_put.h

Coverity reported this leak, which can be fixed by moving the free()
into the same scope as the assignment.

Fix memory leak in target_put

---

pmi-simple/simple_pmi.c

* Fix initialization of socket struct (sin_zero field was uninitialized)
* Check for successful socket creation before using the socket

Simple PMI Fixes

---

test/unit/complex_reductions_f.f90

Instead of `epsilon`, use 1/1000th of a percent (1e-5) tolerance when checking for correctness in the Fortran complex reduction unit test.  We need this because there's a tiny bit of error at relatively large scale, likely because of the numerical non-associativity of parallel reductions.
Addresses issue #439.

Loosen threshold to pass Fortran complex reduction

---

configure.ac

Check for presence of 'data_start' and 'end' symbols on Linux.  Error
output looks like:
checking for data segment pointer... not found
configure: error: Could not locate data segment

Configury: Add check for data segment symbol

---

.travis.yml

To reduce the large # of unit test warnings in Travis...

Ignore deprecated decls for now in Travis (AMO's)

---

mpp/shmem.h4.in
test/unit/Makefile.am
test/unit/c11_test_shmem_atomic_add.c
test/unit/c11_test_shmem_atomic_fetch.c
test/unit/c11_test_shmem_atomic_inc.c
test/unit/c11_test_shmem_atomic_set.c

Note that adding these tests revealed that shmem_atomic_add was mistakenly omitted from the new C11 atomics routines :/

Duplicate C11 AMO unitests to cover some of shmem_atomic_* interface

---

.travis.yml
configure.ac
mpp/shmem_c_func.m4
src/symmetric_heap_c.c
test/unit/Makefile.am
test/unit/complex_reductions_f.f90
test/unit/ipgm.c
test/unit/shmalloc.c
test/unit/shmem_calloc.c
test/unit/shrealloc.c

`shmem_calloc` wraps `dlcalloc` and the `shmem_calloc.c` unit test is similar to the `shmalloc.c` test except that it _adds_ integer values to the allocated buffer instead of _setting_ those values.

Add shmem_calloc and a unit test akin to shmalloc.c

---

.travis.yml
config/opal_check_pmi.m4
configure.ac
src/Makefile.am
src/init.c
src/runtime-pmix.c
src/shmem_internal.h

This PR adds a new `runtime-pmix.c` file which uses the PMIx interface (courtesy of @rhc54 and @angelali4096).  It also incorporates the upstream (OMPI) m4 script for PMI detection, including the `--with-pmix` flag.  Finally, it includes a build of OpenMPI 3.0.x in Travis CI (via RPM) to execute the SOS unit tests using the OMPI (mpiexec) launcher running on top of PMIx.

Add PMIx experimental feature w/ Travis testing

---

src/atomic_c.c4
src/atomic_f.c
src/collectives.c
src/data_c.c4
src/data_f.c4
src/shmem_collectives.h
src/shmem_comm.h
src/shmem_lock.h
src/shmem_synchronization.h
src/synchronization_c.c4
src/synchronization_f.c

Incorporates ctx args into the `shmem_internal` layer.  AMO and RMA routines now call the updated `shmem_internal(ctx,...)` functions.  Uses `SHMEM_CTX_DEFAULT` for the collective, shmem_lock, shmem_ct, and Fortran routines.

Add context argument to shemm_internal routines.

---

configure.ac
mpp/shmem_c_func.h4.in
src/init.c
src/runtime-pmi.c
src/runtime-pmi2.c
src/runtime-pmix.c
src/runtime.h
src/shmem_internal.h

Use language version to decide when to use _Noreturn and [[noreturn]].
This should clean up warnings when building SOS from using _Noreturn
with -std=c99. Transition internal usage back to compiler attributes
instead of _Noreturn to avoid a dependence on C11.
Also, shuffle the attribute location in C++ shmem_global_exit to work
around Clang error.

Cleanup noreturn usage

---

mpp/shmem.h4.in
src/Makefile.am
src/shmem_comm.h
src/shmem_synchronization.h
src/transport_none.c
src/transport_none.h
src/transport_ofi.c
src/transport_ofi.h
src/transport_portals4.c
src/transport_portals4.h

Add the `shmem_ctx_t ctx` argument to each routine in the transport layer (for ofi, portals, and none).

Propagate context argument through the transport layer

---

src/contexts_c.c
src/transport_none.h
src/transport_ofi.c
src/transport_ofi.h
src/transport_portals4.c
src/transport_portals4.h

As a proof-of-concept, set all user-provided contexts to the default context within OFI.  Transport none and portals currently do nothing for ctx_create.
Please feel free to provide feedback before I add a (simple) functional `shmem_ctx_create` for OFI.

 [No merge] Move OFI put/get counters into shmem_ctx_default struct

---

.travis.yml
mpp/shmem.h4.in
mpp/shmemx.h4.in
src/contexts_c.c
src/transport_none.h
src/transport_ofi.c
src/transport_ofi.h
src/transport_portals4.c
src/transport_portals4.h
test/unit/many-ctx.c
test/unit/web.c

Highlights:
- Adds `shmem_ctx_create()` and `shmem_ctx_destroy()` for OFI, based on the [prototype](https://github.com/jdinan/sandia-shmem/tree/contexts).
- Removes the (presumably) extraneous [cntr_info object](https://github.com/jdinan/sandia-shmem/blob/contexts/src/transport_ofi.c#L1252) and renames it to `shmem_transport_ofi_info`.
- Adds a couple endpoints to the ctx struct
To do:
- Initialize the default context with the same routine as user contexts (`shmem_transport_ofi_ctx_init`).
- Do resource cleanup upon error from shmem_ctx_create and address [JD's comments](https://github.com/Sandia-OpenSHMEM/SOS/compare/v1.4.0-dev...davidozog:pr/ctx_create_destroy?expand=1#diff-02eef8be694d26121d1275651d32e9a5R1303).
- Assure this works with latest libfabric:master (`many-ctx` and `web.c` …

First draft of ctx create/destroy

---

man/shmem_test.3
man/shmem_wait.3
mpp/shmem.h4.in
mpp/shmem_c_func.h4.in
src/synchronization_c.c4
test/unit/shmem_test.c

New change that will be incorporated into the next draft of OpenSHMEM 1.4.

Sync API: revert shmem_cmp_t back to int

---

mpp/shmem.h4.in
src/contexts_c.c
src/transport_ofi.c
src/transport_ofi.h

Eliminate sharing of CQs across contexts; this is needed to support the FI_THREAD_COMPLETION model supported by the PSM provider.  Additional changes:
* Destroy the default context using common destroy routine
* Add OFI return code checking macros to clean up/simplify return code checks
* Remove global endpoint (ofi_epfd), replace usage of this with default context CNTR endpoint
* Clean up / rewrite CQ error event reading/reporting code (usage should be reviewed)
* TODO: Move bounce buffer pool to context to prevent deadlock from bounce buffer exhaustion and decrease mutex granularity
* TODO: Add global target endpoint with FI_REMOTE_READ/WRITE and remove these flags from injection-only endpoints in contexts
* TODO: Move STX into the context to eliminate STX (PSM context) sharing …

Move CQ into the context

---

.travis.yml
README
configure.ac
src/shmem_env_defs.h
src/shmem_free_list.c
src/shmem_free_list.h
src/shmem_internal.h
src/transport_ofi.c
src/transport_ofi.h
src/transport_portals4.h

* Establish upper limit on bounce buffer pool size
* Adds SHMEM_MAX_BOUNCE_BUFFERS env var
* Cleans up RMA operation error handling and incorrect CQ usage
* Clean up CQ drain loop
* Move STX into the context (future work, improve STX resource usage)
* Add support for FI_THREAD_COMPLETION via --enable-thread-completion (maybe not the best name, I'm open to suggestions)

Add FI_THREAD_COMPLETION support

---

src/transport_ofi.c

Since we are setting FI_RM_ENABLED on the domain, it's preferred to
allow the provider to select the CQ size in order to allow better
resource management.

OFI: Allow provider to select CQ size

---

src/transport_ofi.h

We were unnecessarily completing nonblocking gets in fence (fetching
atomics are also tracked on the counter, but are blocking and thus
cannot be pending in a call to shmem_fence).  Closes #202.

OFI: Remove get_wait from fence operation

---

src/shmem_internal.h
src/transport_ofi.h

Eliminate locks in FUNNELED and SERIALIZED threading modes and in MULTIPLE mode when the context is PRIAVATE or SERIALIZED.

Eliminate locking, when possible

---

src/transport_ofi.c

Clean up the contexts array code and stop leaking array slots when contexts are freed.

Clean up OFI contexts array

---

src/init.c

Can't use etext, since it may be within read-only text pages.  Can't use
data_start because it breaks library interposition.  Reverting to
data_start until we figure out a solution that works for both.
Closes #555 

Revert 09f8bfad, change from data_start to etext

---

configure.ac

GCC 7 was optimizing away the entries in the configury data segment
check, causing the non-empty check to fail.  Update data segment check
to include a static variable in a function to prevent this from
happening.

Configury: Update data segment check

---

src/contexts_c.c
src/transport_none.h
src/transport_ofi.c
src/transport_portals4.c
src/transport_portals4.h
test/unit/many-ctx.c

This adds the return value to `shmem_ctx_create`, and calls `shmem_transport_ctx_destroy` if a non-zero return value is encountered during the OFI initializations.
The `many-ctx` unit test attempts to initialize as many contexts as possible.  When it does, it destroys some contexts, freeing enough resources to recover for some tests of the atomics (this is needed for the sockets provider, at least).
Note: the `many-ctx` test seems to work fine in Linux, but I've just noticed a seg. fault in OSX that I'm investigating now...

Destroy context upon failure

---

.travis.yml
README
config/check_cma.m4
config/check_gettid.m4
configure.ac
src/shmem_env_defs.h
src/transport_cma.h
src/transport_ofi.c
src/transport_ofi.h

This is a WIP that allocates an array of STXs, with the goal of sharing them based on the thread model and OpenSHMEM context options. It introduces parameters for the maximum array size, as well as the heuristic/algorithm for sharing STXs. Infrastructure is in place for further optimization (based on tid and a private/shared context), and I would appreciate any feedback you can offer before going further. Thanks!

More efficient STX control/sharing

---

src/transport_ofi.c

Fix "warning: function declaration isn't a prototype"

OFI: Fix build warnings

---

NEWS
src/shmem_atomic.h
src/transport_portals4.c
src/transport_portals4.h
test/unit/shmem_ctx.c

Fix several communication tracking/completion races in ```SHMEM_THREAD_MULTIPLE``` mode in the Portals transport.

Fix several communication/tracking completion races in Portals

---

src/transport_ofi.c
src/transport_ofi.h
test/unit/Makefile.am
test/unit/mt_contention.c

In FI_THREAD_COMPLETION mode, accesses to context structure fields are
guarded by a mutex.  Thus, atomics on the pending put/get counters are
an unnecessary overhead.
Closes #546

OFI: Eliminate atomics with FI thread completion

---

configure.ac
src/transport_cma.h
src/transport_ofi.c

Fix CMA build

---

src/shmem_env_defs.h

This must have been an oversight when breaking apart the TX and RX poll limits.  We need to set the poll limit value to either 0 or -1, depending on whether the user passes `--enable-completion-polling` or not.

Use DEFAULT_POLL_LIMIT in shmem_env_defs.h

---

src/transport_ofi.c
src/transport_ofi.h

Non C11 compilers do not allow unnamed union fields (as exposed with `-pedantic`).  I've added the name `val` for the TID value within the `shmem_internal_tid` struct.

Add name to internal tid_t union for non-c11

---

src/transport_ofi.c
test/unit/gettid_register.c

Fix missing ".val" & add static to my_gettid test

---

README
src/shmem_env_defs.h

Set the default value of `SHMEM_OFI_STX_MAX` to 1 instead of 16 so that users do not have to worry about saturating HFI contexts sooner than expected on the PSM2 provider.

Reduce OFI_STX_MAX default value to 1 (for PSM2)

---

src/init.c
src/shmem_internal.h
src/transport_cma.h
src/transport_xpmem.c
src/util.c

When _GNU_SOURCE is enabled (e.g. in CMA builds), the GNU version of
this function (which has a different prototype) is used.  Wrap it for
portability.

Add wrapper for strerror_r

---

src/transport_portals4.c

shmem_transport_ctx_destroy() is already called from cleanup_handles()

Removing duplicated ctx destroy

---

README
src/shmem_env_defs.h
src/transport_ofi.c

This adds an environment variable that disallows private contexts from claiming exclusive access to an STX in the OFI layer.  This may improve performance for multi-threaded apps that use more exclusive thread-private contexts than available STXs.

Add env var to disable private contexts in OFI

---

configure.ac
src/shmem_synchronization.h
src/transport_none.h
src/transport_ofi.c
src/transport_ofi.h
src/transport_portals4.h

Adds a static inline `shmem_transport_probe()` routine for making manual-progress and the `--enable-manual-progress` configure option to enable intermittently calling the routine.  In the OFI transport, the probe reads the target (RX) counter.  In other transports, a probe does nothing.
If enabling manual progress, the OFI probe routine is called in "put_quiet", and "get_wait" and the various "shmem_wait" routines.  We might want to think about placing the probe elsewhere as well, especially for the case with multiple STX's on the libfabric PSM2 provider.

Add probe routine for making manual progress

---

configure.ac
src/transport_portals4.c
src/transport_portals4.h

NB fence is an interesting optimization that automatically delays fence operations to improve overlap.  However, the implementation has poor threading performance, is unmaintained, and is poorly tested.  Users can also achieve this optimization at the application layer (and arguably, this is preferred anyway since the optimization becomes portable across SHMEM libraries) by delaying fences as follows:
```
shmem_put(...);
shmem_fence();
compute(...);
shmem_put(...);
```
Into this:
```
shmem_put(...);
compute(...);
shmem_fence();
shmem_put(...);
```

Remove NB fence prototype from Portals transport

---

NEWS
configure.ac

I've added SOS updates since 1.4.0 to the NEWS file.
@jdinan and @wrrobin, please let me know if I've missed anything or should re-word what's there now.  Thanks!

Bump version, and update NEWS for 1.4.1rc1

---

src/transport_portals4.h

use the CT handle attached to the PtlAtomic routine,
when waiting ACKs.
The CT handle (PtlCTWait argument) must match with
the MD handle (PtlAtomic argument).
Signed-off-by: Nicolas Chevalier <nicolas.chevalier@bull.net>

Fix Atomic inc (Portals4)

---

src/transport_ofi.c

Disable the FI_REMOTE_READ/WRITE capabilities on the counter endpoint.  Leaving
these caps enabled causes the PSM2 provider to allocate an extra PSM2 context
in libfabric v1.6.0 and later, leading to a resource exhaustion issue.
Closes #695

OFI: Disable target caps on cntr EP

---

test/unit/reduce_active_set.c

Signed-off-by: Thomas Naughton <naughtont@ornl.gov>

Fix typo to init min_psync[] in unit test

---

mpp/shmem.h4.in
mpp/shmemx.h4.in
src/transport_ofi.c
src/transport_ofi.h

* Add bounce buffer performance counters
* Add debug message to print diagnostic info upon context destruction
* Fix type issue with SHMEM_CTX_* constants (int implicitly promoted to long)

Add bb performance counters

---

src/transport_ofi.c

FI_MR_SCALABLE is "old" (pre v1.5) OFI mr_mode
(still supported for backward compatibility)
that must not be mixed with new API mr_mode bits.
Signed-off-by: Matias Cabral <matias.a.cabral@intel.com>

Fix FI_MR_RMA_EVENT used with FI_MR_SCALABLE.

---

configure.ac

Manual progress should enable completion polling so that `shmem_transport_probe()` is called in `put_quiet` and `get_wait`, as described in issue #715.
FWIW, I tested the performance of this change using the PSM2 provider in our uni-directional throughput and halo exchange benchmarks, and I didn't notice any substantial difference.

Manual progress should also do completion polling

---

src/shmem_atomic.h

Signed-off-by: Srđan Milaković <sm108@rice.edu>

Fix inline assembly for SPINLOCK_BODY for aarch64.

---

.travis.yml
Makefile.am
configure.ac
sandia-openshmem.spec.in
src/Makefile.am
src/sandia-openshmem.pc.in

* Update RPM build to cleanly uninstall when `%{_prefix} != /usr`
* Installs docs (README, LICENSE, etc.) under /usr/share as part of standard installation (simplifies RPM)
* Rename packaging from sos to sandia-openshmem to avoid name conflict with https://github.com/sosreport/sos

Update RPM Build

---

.travis.yml
README
configure.ac
pmi-simple/Makefile.am

* Removes `--disable-mr-scalable` and `--enable-mr-rma-event` and replaces with `--enable-ofi-mr={basic, scalable, rma-event}`
* Fixes `make distcheck` target with simple PMI
* Improves build configuration output from configure
* Renames `--with-total-data-ordering` to `--enable-total-data-ordering`

Configury updates

---

config/check_sched_getaffinity.m4
configure.ac
src/init.c

I found this output useful for understanding what exactly is happening when passing process affinity options to the launcher such as `--bind-to core:2` or `--bind-to socket:1`.  Because it depends on `sched_getaffinity`, it'll only work in Linux.

Check for sched_getaffinity, and include in DEBUG

---

test/apps/gups.c

Fix overflow warning in GUPS

---

src/transport_ofi.c

This appears to work fine with the sockets provider.  Needs to be tested with the PSM2 provider.
Closes #765

OFI: Only bind target cntr to MRs, not EP

---

src/transport_ofi.c
src/transport_ofi.h

We may also want to ensure that we perform completion polling when `USE_CTX_LOCK` is enabled and the threading level is `SHMEM_THREAD_MULTIPLE`.

Release the ctx lock while blocked

---

src/init.c

malloc return value not checked reported by Klocworks.
Signed-off-by: Matias A Cabral <matias.a.cabral@intel.com>

Check malloc return value during init.

---

src/runtime-pmi.c

Security KW finding not limiting strncpy to destination buffer length
Signed-off-by: Matias A Cabral <matias.a.cabral@intel.com>

Sanity check on PMI max key/val length

---

.travis.yml

There is an issue with `tests-mellanox` that is causing our test suite to report failures.  A fix to that issue is here: https://github.com/openshmem-org/tests-mellanox/pull/38
We should just comment out this test for now, and bring it back after the fix is merged.

Comment out test-mellanox's basic:static test

---

src/transport_ofi.c

I believe these `size_t` values should have the `%zu` format, correct?  Otherwise, I occasionally see negative numbers for the max message size (see issue #816).
With this change, I see what appears to be `SIZE_MAX` (18446744073709551615) for the max_msg size on my Mac with sockets.  Is that expected?  Seems too large to me...

OFI: Fix format specifier for size_t values

---

src/init.c
src/shmem_internal.h

A few updates to build the full affinity message into the string buffer so it can be wrapped.
```
Sandia OpenSHMEM 1.4.2
Build information:
Git Version           v1.4.2-104-gcd14f8e2 (master)
Configure Args        '--enable-pmi-simple'
'--with-ofi=/home/dinanjam/opt/libfabric-dev'
'--disable-libtool-wrapper' '--enable-picky'
'--enable-manual-progress'
'--prefix=/home/dinanjam/opt/sos-dev'
Build Date            Tue Dec 18 12:28:08 CST 2018
Build CC              gcc -std=gnu99
Build CFLAGS          -g -O2 -Wall -Wno-long-long -Wmissing-prototypes
-Wstrict-prototypes -Wcomment -pedantic -rdynamic 
[0000] DEBUG: ../../src/init.c:333: shmem_internal_init
[0000]        Thread level=SINGLE, Num. PEs=1
[0000]        Sym. heap=0x80000000 len=537919488 -- data=0x601050 len=8
[0000] DEBUG: …
```

Wrap affinity debug message

---

README.md

This links the SOS logo to the official master-branch location and changes the version badge to use [img.shields.io](https://img.shields.io), which appears to be less finicky than [badge.fury.io](https://badge.fury.io).
Side note: the landing page for the Travis badge (which defaults to the latest PR, not the latest master build) appears to be a "won't fix" issue that's been closed years ago:
https://github.com/travis-ci/travis-ci/issues/655
https://github.com/certbot/certbot/issues/927
I think our valid options are to 1) leave it as is, 2) remove it, 3) link to the ["branches" page](https://travis-ci.org/Sandia-OpenSHMEM/SOS/branches), or 4) link to the ["builds" page](https://travis-ci.org/Sandia-OpenSHMEM/SOS/builds).  I don't see any way to link to the latest master build...

Minor README patches

---

.travis.yml

- use distro provided `libevent` and `hwloc` to reduce build time
- use `prun -terminate` in order to kill the `prte` daemon (instead of `killall prte`)
- use `prun --daemonize` in order to start the `prte` daemon (instead of `prte&; sleep2`)

travis: misc prrte related changes

---

mpp/shmem-def.h.in

A developer/collegue reported a C++ error in regards to our `shmem_ctx_t` dummy struct:
`...<unnamed struct> declared using unnamed type, is used but never defined`.
C++ apparently does not support anonymous structs, so we might need to give it a name.
Note: this name is technically not allowed by the OpenSHMEM specification - perhaps we should propose a sub-namespace such as `shmem_impl_*` to address this?  See [this ticket](https://github.com/openshmem-org/specification/issues/262).

Add name to shmem_ctx_t dummy struct for C++ fix

---

src/runtime-pmix.c

* nspace field size is `PMIX_MAX_NSLEN+1`
* npes type is `uint32_t`
* be safer about signed/unsigned type conversions

Minor cleanups to PMIx runtime code

---

.travis.yml
src/transport_ofi.c
src/transport_ofi.h

With this patch, manual progress no longer requires the target cntr and can be independent of hard polling in wait operations.

Add target CQ and use for manual progress

---

configure.ac
src/shmem_env.c

Implements proposed extension: https://github.com/openshmem-org/specification/pull/200
Does not return an error value from `shmem_init_thread` as suggested in the proposal.

Add support for decimal values in SHMEM_SYMMETIC_SIZE

---

src/shmem_internal.h

Don't print the PE id before it's been set.  This error macro is used during PMIx startup.
Before:
```
[????] ERROR: ../../src/init.c:174: shmem_internal_init
[-001]        Something bad happened
```
After:
```
[????] ERROR: ../../src/init.c:174: shmem_internal_init
[????]        Something bad happened
```

Fix preinit error message output

---

src/transport_ofi.c

When `ctx_destroy` is called to clean up a failed `ctx_init` operation, the debug message could dereference null pointers to the FI cntrs on the context.  Add check before dereferencing these pointers.

Don't deref null fi_cntr pointer in debug msg

---

src/init_c.c

This fixes an undefined reference to `pshmem_global_exit`, due to a missing weak symbol declaration.

Add weak symbol definition for shmem_global_exit

---

.travis.yml
README
src/collectives.c
src/shmem_collectives.h
src/shmem_env_defs.h
test/unit/Makefile.am

Notes:
* This algorithm also does not use one-sided atomics (yay!)
* This algorithm can be used back-to-back with the same psync and active set
Note for review: We should re-evaluate auto selection of the reduction algorithm to determine when AMO-based reductions versus SW reductions should be used and how to account for scale and message size.

Add bandwidth optimal ring all-reduce

---

src/transport_ofi.h
src/transport_portals4.h

Surprised that these redefines weren't generating warnings.

Remove duplicate transport-level datatypes

---

src/contexts_c.c
src/shmem_synchronization.h

This addresses a change from https://github.com/openshmem-org/specification/pull/222 : shmem_ctx_destroy, fence, and quiet perform no operation when the input context is invalid.

If context is invalid, return immediately from fence, quiet, destroy

---

NEWS
configure.ac
scripts/simple-build-ofi.sh

SOS v1.4.4 updates

---

test/apps/gups.c

Removed barrier calls from `UpdateTable` to the main function. Two benefits:
1. This will remove one redundant barrier call in the current code.
2. `UpdateTable` can easily be implemented with threads without the need to sync among threads.

Re-organized barrier in gups to remove one redundant barrier call

---

test/shmemx/Makefile.am

This reminds me that the shmemx wait/test any/all/some tests should be moved out of shmemx.  I created issue #891 (and see #863 and #892). 
@jdinan, please let me know if you'd rather address those issues before merging this PR.

Fix and re-arrange which shmemx tests are built

---

src/shmem_atomic.h
src/shmem_comm.h
src/shmem_lock.h
src/shmem_synchronization.h
src/synchronization_c.c4
src/transport_ofi.c
src/transport_ofi.h
src/transport_portals4.c
src/transport_portals4.h

Updates to the utility atomics (spinlocks and counters) to use `__atomic` rather than deprecated `__sync`, inline assembly, and compiler fences.  Rename the thread-safe counter routines to avoid name confusion with `shmem_internal_atomic_*` API used to implement the AMOs.

Updates to utility atomics

---

src/shmem_atomic.h
src/shmem_collectives.h
src/shmem_synchronization.h
src/synchronization_c.c4

These are the same memory syncs we do before returning from wait/test
operations to ensure shared memory updates and remote updates cached in
the NIC are visible in memory.

Add memory sync before returning from barriers

---

src/shmem_team.c
test/shmemx/Makefile.am
test/shmemx/shmemx_team_max.c

This PR addresses the issue in #909 where a program that runs out of team resources aborts unnecessarily.
I added a couple comments to clarify the delayed return when no psync is available.

Teams: Warn when psync unavailable & add comments

---

src/shmem_team.c
test/shmemx/shmemx_team_max.c

With upcoming changes to the teams proposal [(#305)](https://github.com/openshmem-org/specification/pull/305/), we need to guarantee that the return values are equal across PEs after team creation.  We can also check whether the reduction is successful in the `shmemx_team_max` unit test.

Reduce return value across PEs during team creation

---

mpp/shmemx.h4
mpp/shmemx_c_func.h4
src/synchronization_c.c4
test/shmemx/c11_test_shmemx_test.c
test/shmemx/shmemx_test_all.c
test/spec-example/shmemx_test_any.c
test/spec-example/shmemx_wait_until_any.c
test/spec-example/shmemx_wait_until_some.c

* add `status` array to `shmem_test_all`
* make `status` a const
* remove updates to `status` when conditions are satisfied
* update corresponding unit tests
* fix compiler comparison warnings with a cast

Wait/test: update "status" semantics to match spec

---

src/transport_ofi.c
src/transport_ofi.h

Update SOS to use MR mode flags instead of deprecated `FI_MR_SCALABLE` and `FI_MR_BASIC` modes. This update requires SOS to be able to deal with the individual modes in basic support being selectively enabled by the provider. In cases where SOS is compiled with basic support, but some of the MR mode flags are cleared by the provider, SOS still builds and populates translation tables even though all entries have the same value (room for future optimization).
Note, this PR does not add support for `FI_MR_LOCAL` SOS level registration of local communication buffers. We don't have a provider that requires this yet and it will be a fairly significant chunk of work to add.
Closes #900

Update to new OFI MR modes

---

src/shmem_team.c
test/shmemx/Makefile.am
test/shmemx/shmemx_team_reuse_teams.c
test/shmemx/shmemx_team_split_2d.c

The 2D team split operation was neglected a bit during the development of `shmem_team_split_strided`, so it's missing some important properties:
* PE numbers must be w.r.t. the team indexing
* updates to the PE strides must be w.r.t. the team's stride
* The returned team object(s) should be the one(s) containing my PE
I believe these changes more-or-less fix the issues we are seeing in the 2D example in #918.

Fix several bugs in the team_split_2D operation

---

test/spec-example/shmemx_wait_until_any_vector.c

I caught a compilation error while testing an older compiler without C11 support  (gcc 4.8.5).
In `test/spec-examples`, it looks like we're using the C interfaces in many places where C11 is used... It seems like the path of least resistance for now, but I'll create a low-priority issue for this.

Use standard C interface in spec-tests (for now)

---

NEWS
configure.ac

Here is a draft of the `NEWS` file for a v1.4.5 release.  Am I missing anything?
With regard to the open PRs, I think #929 might be ok to include in v1.4.5, but everything is tested except for that change... (except Portals, still need to check that).  #918 may change as v1.5 of the OpenSHMEM specification is released, so I tend to think we should defer that one.  Thoughts @jdinan and @wrrobin?

Update NEWS and MAJOR/MINOR_VERSION for v1.4.5

---

test/shmemx/c11_test_shmemx_test_vector.c
test/shmemx/c11_test_shmemx_wait_until_vector.c

The compiler warns about these comparisons when using `-Wall -Wextra` flags.

Resolving comparison warnings in p2p vector tests

---

src/teams_c.c4

I believe this is a bug.  The spec says,
> If team compares equal to SHMEM_TEAM_INVALID, then a nonzero value is returned and ctx is set to SHMEM_CTX_INVALID.

Set ctx to SHMEM_CTX_INVALID if team is invalid

---

.travis.yml
config/ompi_check_ucx.m4
configure.ac
src/Makefile.am
src/runtime-mpi.c
src/runtime-pmi.c
src/shmem_comm.h
src/shmem_env.c
src/shmem_env_defs.h
src/transport.h
src/transport_ucx.c
src/transport_ucx.h

This PR adds an SOS transport that uses the UCX/UCP interfaces. It fully supports all of the OpenSHMEM interfaces, but has not been tested/optimized for performance. A known limitation is that there are currently no context-related optimizations.

UCX Transport

---

src/symmetric_heap_c.c

To comply with the spec, if size or count is 0, then the `shmem_calloc` routine should not be semantically equivalent to `shmem_barrier_all` 

Allocation routines return if any of the arguments are passed zero value

---

src/atomic_c.c4

Remove ctx check on deprecated shmem_swap routine

---

test/spec-example/Makefile.am
test/spec-example/shmem_reduce_example.c
test/spec-example/shmem_team_context.c
test/spec-example/shmem_team_split_2D.c

This is a spin-off PR of #907, which now adds the teams example programs as tests in the `spec-example` directory.
Currently, the tests/examples are not passing due to the issues mentioned in #907.  Minor modifications have been made (`shmem` -> `shmemx`) so that the programs compile with SOS, but they are otherwise very similar to the upstream versions (including filenames).

Add teams spec tests to "spec-example" directory

---

configure.ac

I encountered this problem when testing Portals4 on a system with libfabric automatically detected.  It's the same issue as #954, which should be resolved by this PR.
Thanks for the patch @jdinan!

Resolve configury issue with multiple transports detected

---

src/shmem_internal.h
src/shmem_team.c

Please see #960 and #963 for a summary of the bug fixes and the addition of a quiet operation to `shmem_internal_choose_pync`.

Teams bug fixes

---

.travis.yml
configure.ac

This includes various updates to make Travis go green again.
An alternative to the PRRTE/PMIx changes below is to disable it entirely temporarily, as in #964.
Here is a summary of the changes:
* Update PRRTE launch commands to latest version
* Checkout stable PRRTE/PMIx commits in Xenial Travis
* Remove Portals+PMIx Travis row (libev is required by Portals, but not working with latest PRRTE/PMIx)
* Switch to libevent 2.1.10-stable for PRRTE/PMIx
* ~~Force UH tests to use prun in PMIx rows~~
* Remove external tests from UCX rows in Travis
* Remove external test from manual-progress row in Travis

Slim down Travis CI

---

mpp/shmem.h4
test/unit/shmem_team_collect_active_set.c
test/unit/shmem_team_max.c

Building with `-std=c99` fails on the tests with the following error:
```
../../../test/unit/shmem_team_collect_active_set.c:108:32: error: too few arguments to function call, expected 4, have 1
shmem_sync(new_team);
~~~~~~~~~~         ^
../../mpp/shmem.h:1383:1: note: 'shmem_sync' declared here
SHMEM_FUNCTION_ATTRIBUTES void shmem_sync(int PE_start, int logPE_stride, int PE_size, long *pSync);
^
../../mpp/shmem.h:36:40: note: expanded from macro 'SHMEM_FUNCTION_ATTRIBUTES'
^
1 error generated.
```
There are also issues with the spec examples with `CFLAGS=-std=c99`. Not sure how to handle those.

Fix C99 header issue

---

src/transport_ucx.h

Addresses one of the issues on #974

UCX: Flush instead of fence with shared memory

---

test/unit/shmalloc.c
test/unit/shmem_calloc.c

These tests fail when `nProcs` is 1 because they try to allocate a buffer with zero size while expecting a valid pointer.  Updating the tests so they don't fail in that case.

Update tests for shmalloc & shmem_calloc when size is zero

---

test/spec-example/Makefile.am

It looks like we may have missed this during code review:
* The spec-examples are not shmemx in v1.5, so we can remove the `SHMEMX_TESTS` guard in the Makefile 
* `shmem_team_sync` and `shmem_reduce_example` require c11, so we can guard those w/ `if HAVE_C11`
This should address #977

Update spec-examples Makefile.am for v1.5

---

.travis.yml
NEWS
configure.ac
sandia-openshmem.spec.in
src/shmem_internal.h
src/shmem_team.c
test/performance/shmem_perf_suite/README
test/performance/shmem_perf_suite/bw_common.h
test/performance/shmem_perf_suite/common.h
test/performance/shmem_perf_suite/latency_common.h
test/unit/query_thread.c

I went ahead and created a `v1.4.x` branch on SOS that is synced with the `v1.4.5` tag.
This PR cherry-picks several commits from the master branch to include in `v1.4.x` to fix some bugs and have a useful Travis script.  Here's a short list of what's included:
* 8de8a785075b3cf5498c8753d98814506ce5e396 to allow higher thread levels in the tests and adds to `v1.4.x`. 
* All commits from PR #968 (teams bug fixes)
* ea3ea06749af57fb12fb48ddac23eaf6ca01244f to fix XPMEM testing in Travis
* A manual merge of the updates from PR #966  (primarily to update PMIx support in Travis)
I'll also add the shmem_perf_suite trial multiplier in PR #988 (and sync with https://github.com/openshmem-org/tests-sos) to `v1.4.x` after it's approved/merged into master.
All should feel free to request other …

(v1.4.x) cherry-pick features/fixes ahead of v1.4.5

---

test/unit/shmem_malloc_with_hints.c

This test is calling a reduction on the pSync so the size should be `SHMEM_REDUCE_SYNC_SIZE`, not `SHMEM_ALLTOALL_SYNC_SIZE`.

Fix pSync size in shmem_malloc_with_hint unit test

---

.travis.yml
src/transport_ucx.c
src/transport_ucx.h

Update the UCX transport to use the new ucp_put_nbx function. Fixes the request
initialization/callback race with the ucp_put_nb API and removes the valid flag
workaround that required the callback to busy wait until the request object was
initialized.
Signed-off-by: James Dinan <jdinan@nvidia.com>

UCX updated to use put_nbx

---

src/runtime-pmi.c

Valgrind says there's a consistent 1KB leak here, but only when NPES == 1.
The problem appears to be that the address of `kvs_value` was being set, so it becomes an invalid free during finalization.  Setting the value instead seems to be the original intent.

Fix small leak on kvs_value in runtime-pmi.c

---

mpp/shmem_c_func.h4
test/apps/gups.c
test/performance/shmem_perf_suite/common.h
test/performance/tests/msgrate.c
test/unit/alltoall.c
test/unit/alltoalls.c
test/unit/bcast.c
test/unit/bcast_flood.c
test/unit/broadcast_active_set.c
test/unit/collect.c
test/unit/collect_active_set.c
test/unit/fcollect64.c
test/unit/nop_collectives.c
test/unit/self_collectives.c
test/unit/sync-size.c

Includes deprecation attributes for these routines:
* shmem_collect32, shmem_collect64, shmem_fcollect32, shmem_fcollect64
* shmem_alltoall32, shmem_alltoall64, shmem_alltoalls32, shmem_alltoalls64
* shmem_broadcast32, shmem_broadcast64
Addresses issue #998

Add deprecation warnings to 32/64-bit collectives

---

test/unit/cxx_test_shmem_atomic_add.cpp

Otherwise, the fetch_add API is redundantly
tested twice

Place deprecated tests rightly

---

test/unit/cxx_test_shmem_atomic_inc.cpp

Otherwise the fetch_inc API is
redundantly tested.

Place deprecated INC tests rightly

---

.travis.yml

* Remove some Portals4 testing rows
* Add a row to enable deprecated API tests
For those unaware, Travis CI has changed it's billing policies so we can no longer rely on it for a wide variety of long-running tests.  I applied for SOS to receive free Open-Source-Software (OSS) credits, but currently we only have ~25k credits (core-minutes).  That's _total_ credits... like forever.  That would give us only ~2 full SOS builds.  I asked if we can get recurring plan, but responses from Travis support are very slow.
For now I propose we slim down Travis as much as we can by disabling all external tests and removing some portals4 rows.  Hopefully this buys us a little time to figure out a more thorough CI strategy (likely using a Jenkins backend).

Disable all external Travis CI tests for now

---

test/shmemx/cxx_test_shmem_atomic_add.cpp
test/shmemx/cxx_test_shmem_atomic_and.cpp
test/shmemx/cxx_test_shmem_atomic_cswap.cpp
test/shmemx/cxx_test_shmem_atomic_fetch.cpp
test/shmemx/cxx_test_shmem_atomic_inc.cpp
test/shmemx/cxx_test_shmem_atomic_or.cpp
test/shmemx/cxx_test_shmem_atomic_swap.cpp
test/shmemx/cxx_test_shmem_atomic_xor.cpp

Addresses issue #800.
To summarize, we renamed the NBI atomics (ratified in OpenSHMEM v1.5) from `shmemx_` to `shmem` for the v1.5.0 release, but we decided to keep the tests exercising the C++ polymorphic bindings in `test/shmemx`.  We intended to remove the checks for `ENABLE_SHMEMX_TESTS` in those tests, but must have forgotten to do it for v1.5.0.

Remove check for SHMEMX_TESTS for C++ NBI atomics

---

.github/workflows/ci.yml
mpp/shmem_c_func.h4
src/shmem_synchronization.h
src/synchronization_c.c4
test/unit/Makefile.am
test/unit/signal_wait_until.c

This implements `shmem_signal_wait_until` and adds a simple unit test.
`shmem_signal_wait_until` differs from the other `wait_until` operations in that it returns the contents of the signal data object that satisfied the wait condition.  I plumbed that through `shmem_synchronization.h` without affecting the other `wait_until` routines, but there may be a cleaner way to do it.
I also included a fix to the GitHub workflow where "sudo make install" was done in user-space and resulted in some funny permission issues on my fork's CI.  @kholland-intel - there is a chance this could be related to the problem on #1027.  It might be worth trying a cherry-pick of https://github.com/Sandia-OpenSHMEM/SOS/commit/12d3e4b2fe8e668879177827d92ebfe68d955127.

shmem_signal_wait_until

---

test/unit/signal_wait_until.c

This resolves several compiler warnings when comparing ints in the following unit test:
```
../../../test/unit/signal_wait_until.c:68:16: warning: comparison of integers of different signs: 'uint64_t' (aka 'unsigned long long') and 'int' [-Wsign-compare]
if (retval > npes)
...
```

Fix warning comparing ints in signal_wait test

---

NEWS
configure.ac
scripts/simple-build-ofi.sh

This updates the version number according to the [Release Checklist](https://github.com/Sandia-OpenSHMEM/SOS/wiki/Release-Checklist) for v1.5.1 release candidate 1.
After it's merged, I'll tag the repository with `v1.5.1rc1`.

Update version numbers and NEWS for v1.5.1rc1

---

src/collectives_c.c4
src/data_c.c4
src/shmem_internal.h
src/synchronization_c.c4
test/unit/Makefile.am
test/unit/bcast_in_place.c
test/unit/waituntil.c

Features:
* Fixes bug for in-place broadcasts (on the root PE).
* Adds error-checking macro for proper buffer overlap.
* No support yet for the strided APIs and put w/ signal.
* Adds a simple unit test for in-place broadcast.

Error-checking: Add checks for dst/src overlap

---

src/transport_ofi.c

When the struct fi_context2 is required by provider/application, disable bounce buffering.
Signed-off-by: Thomas Huber <thomas.huber@cornelisnetworks.com>

Disabling bounce buffering when struct fi_context2 is required

---

src/init.c
test/unit/iput128.c

On MacOS, there's a problem with the initialization of the symmetric data segment (the symmetric heap is fine).  I can reproduce it on a 2020 M1 MacBook Pro, but not a 2016 Intel MacBook Pro.
SOS uses `get_etext` and `get_end` to find the data segment region, but [the manpage says](https://www.manpagez.com/man/3/get_etext/), "Use of these routines is very strongly discouraged.  The problem is that any program that is using UNIX link editor defined symbols (_end, _etext or _edata) is making assumptions that the program has the memory layout of a UNIX program."  I can tell that the determined memory layout is wrong on the M1 Mac, which causes any use of a global or static variable in an SOS communication routine to go out of bounds. 
It seems `mach_vm_region` is the standard API for …

Patch data segment init for M1 (and M2?) Macs

---

.gitignore
mpp/pshmem.h4
mpp/shmem-def.h.in
mpp/shmemx-def.h
mpp/shmemx.h4
src/symmetric_heap_c.c
test/shmemx/Makefile.am
test/shmemx/shmem_malloc_with_hints.c
test/unit/shmem_malloc_with_hints.c

Implemented a SHMEMX_NO_BARRIER hint for shmem_malloc_with_hints. This hint provides users with a way to bypass the barrier that occurs from within a shmem_malloc. Also, added a unit test for this hint.

Add support for a SHMEMX_NO_BARRIER hint

---

configure.ac
src/shmem_synchronization.h
src/transport_ofi.c
src/transport_ofi.h

Signed-off-by: Md Rahman <md.rahman@intel.com>

Enable OFI provider for Slingshot

---

src/init.c

Just fixing a couple compiler warnings I noticed on Mac.  The `get_base_address` function should be `static` qualified and the arithmetic on `void *` is only allowed as a GNU extension.  Casting to `char *` should fix that for now.

MacOS: fix compiler warnings (static, void* arith)

---

src/transport_ofi.c

Signed-off-by: Thomas Huber <thomas.huber@cornelisnetworks.com>
In `transport_ofi.c` there are two instances of behavior that might be a small violation of the libfabric man pages. Both instances are related to setting the capabilites (caps) for tx_attr->caps and rx_attr->caps
1. In function `shmem_trasnport_ofi_target_ep_init(void)`
- The general caps are set to `info->p_info->caps = FI_RMA | FI_ATOMIC | FI_REMOTE_READ | FI_REMOTE_WRITE` which overwrites whatever what returned in call to `get_info()`
- Meanwhile, the `info->p_info->tx_attr->caps` are still set to whatever was returned by `get_info()`
- Following this, calls to `fi_endpoint()`, `fi_cq_open_fi_ep_bind()`, and `fi_enable()` are made
- In the manpages for `fi_endpoint()` …

Setting the rx capabilites and tx capabilites to 0

---

NEWS
configure.ac
scripts/simple-build-ofi.sh

This updates the version number according to the [Release Checklist](https://github.com/Sandia-OpenSHMEM/SOS/wiki/Release-Checklist) for v1.5.2 release candidate 1.
After it's merged, I'll tag the repository with v1.5.2rc1.

Update version to v1.5.2rc1 in configure.ac, NEWS file, and simple build script

---

configure.ac

This fixes a build issue when using newer versions of the oneAPI C compiler (icx), to build SOS.  Support for C11 generics is not correctly detected. 
(@wrrobin @kholland-intel - I think I was wrong when I mentioned there was a problem with fixed-width types and oneAPI compilers. Something like what's in this PR should be all that's needed.)
I didn't work too hard to generally support fortran cause it's deprecated, but I left a note 😄.  It seems to work with `ifort` and `ifx` seems to work with autoconf >= v2.70.

Configury: Add patches to support oneAPI compilers

---

src/transport_ofi.c

Adding FI_RECV flag to ctx init caps

---

bindings/generate_bind_cxx_extras.cpp
bindings/shmem_bind_cxx.m4

@davidozog - The change you pointed out made sense. This PR handles it. Please check.

Bitwise amo cpp bindings: removed fixed width from check

---

LICENSE
test/unit/nop_collectives.c
test/unit/self_collectives.c
test/unit/shmem_team_max.c
test/unit/to_all.c

This addresses issue #1097.
Signed integer types that are not fixed-width are deprecated in OpenSHMEM v1.5, so we should remove the corresponding tests for the sake of other libraries using the SOS test suite.
This PR just removes the instances from the tests.  The next step might be to mark the routines as deprecated, or possibly remove them.

Remove unsupported signed reductions tests for v1.5

---

test/include/Makefile.am
test/include/tests_sos/wtime.h
test/unit/bcast_flood.c
test/unit/bigget.c
test/unit/bigput.c
test/unit/fadd_nbi.c
test/unit/lfinc.c
test/unit/spam.c

This is intended to help users of the https://github.com/openshmem-org/tests-sos repository to build the test suite even when the OpenSHMEM library does not define `shmemx_wtime()` (e.g., OSHMPI).

tests: Replace shmemx_wtime() with tests_sos_wtime

---

mpp/shmemx-def.h
src/shmem_team.c
src/shmem_team.h
test/shmemx/Makefile.am
test/shmemx/shmemx_team_host.c
test/shmemx/shmemx_team_node.c

This should be handy for supporting multi-NIC and/or topologically-aware collectives.
@wrrobin - perhaps this could be named `SHMEMX_TEAM_NODE` because it's relying on PMI's notion of a "node" (via `shmem_runtime_get_node_rank()`).  Here is a short summary of where this info comes from across the SOS "`runtime-pmi`" options:
- PMI1: `gethostname`
- PMI2: `gethostname`
- PMIx: `PMIX_LOCAL_PEERS` query
- MPI:  Split of type `MPI_COMM_TYPE_SHARED`
But `SHMEMX_TEAM_HOST` is fine with me if that's preferred/simpler.

Teams: add SHMEMX_TEAM_NODE

---

src/shmem_compiler_script.in

This adds a `-showlibs` flag to the compiler wrappers, which is useful for getting only the linking flags.

Compiler wrapper: add -showlibs flag for link line

---

src/synchronization_c.c4

Currently the **shmem_test_all** API does not account for elements that are suppose to be ignored (as set by the **status** argument) when determining the return value.

src: Fix bug in SHMEM_DEF_TEST_ALL

---

src/transport_ofi.c

This PR makes a minor bug fix to the code that is responsible for generating a list of providers that have NIC information. This should resolve the issues we were seeing on some of our development systems that have a single NIC when SOS is being used with multi-NIC functionality enabled.

Multi-NIC Bug Fix: Set 'next' attribute of list tail to NULL

---

.github/workflows/ci.yml
mpp/shmemx.h4
mpp/shmemx_c_func.h4
src/data_c.c4
src/shmem_internal.h

Adding implementations for IBPUT/IBGET APIs that will be part of a future OpenSHMEM specification. See specification details regarding these functions [here](https://github.com/openshmem-org/specification/pull/448).
Initially, these functions will be added as extension APIs.

Add ibput and ibget as extension APIs

---

src/collectives_c.c4
src/data_c.c4
src/shmem_internal.h
src/synchronization_c.c4

Now checking if an object resides on the external heap when determining if said object is symmetric. This PR also revises the overlap check to allow overlap in target and source buffers for RMA operations if `target_pe != source_pe`

Add error checking for objects on external heap

---

src/data_c.c4

Small fix to add precheck parameter to overlap check for ibput/ibget APIs

src: Add overlap check to fix ibput/ibget APIs

---

.gitmodules
src/shmem_team.c
src/teams_c.c4

This resolves the issue discovered by @ronawho regarding unit test `shmem_team_get_config` here:
https://github.com/openshmem-org/tests-sos/pull/37
~~This is just a temporary patch to better align with the API spec.  SOS still effectively ignores the `num_contexts` hint, so #1019 is not quite addressed.~~
This also addresses #1019

num_contexts patch

---

pmi-simple/Makefile.am
pmi-simple/mpir_mem.h
pmi-simple/mpl_sockaddr.c
pmi-simple/mpl_sockaddr.h
pmi-simple/simple_pmi.c

This requires some slight modifications for SOS:
* include `"config.h"` instead of `"mpichconf.h"`
* define `MPI_MAX_PORT_NAME `manually (w/out including `"mpi.h"`)
* carry new pmi-simple requirements from MPICH (`mpir_mem.h`/`mpl_sockaddr.h`)
* ignore `strncasecmp`/`strnicmp` requirement (not used in pmi-simple)
I'm not sure we want to make this change, but it does eliminate several warnings we see in our current version of pmi-simple.  If we include it, we may want to defer this for a later SOS release (e.g., v1.5.2).

Topic: pmi-simple - update to upstream (MPICH) state

---

mpp/shmemx_c_func.h4
src/shmem_team.c
src/transport_ofi.c

These are small fixes for compiler warnings found with `--enable-pedantic`.

fix pedantic compiler warnings

---

src/shmem_comm.h

This PR makes it such that **shmem_internal_copy_self** will always wait until any pending put operations are complete before returning.
For example, when using OFI with bounce buffers enabled it is possible that **shmem_internal_put_nb** will not increment the **completion** value. If **completion** is zero, the call to **shmem_internal_put_wait** will not wait for completion of pending/ongoing put transactions before returning, even though the intent of **shmem_internal_copy_self** is to be blocking.

src: Bug fix in shmem_internal_copy_self

---

.github/workflows/ci.yml
configure.ac
src/shmem_comm.h

This PR adds support to optionally disable non-fetch AMO and instead fetch AMO. This is due to a bug with non-fetch AMO on CXI provider that gets stuck after a certain number of operations when optimized MR mode is not used. This is a temporary work-around and may be removed as the original bug is resolved.

Option to disable non-fetch AMO

---

src/collectives.c
src/shmem_comm.h

This PR extends the support of the **--disable-nonfetch-amo** configuration option to avoid the use of non-fetching atomics in **shmem_internal_op_to_all_linear** and **shmem_internal_op_to_all_tree**

Add DISABLE_NONFETCH_AMO support to op_to_all implementations

---

src/transport_ofi.c

This PR adds a fix to an issue detected by Coverity where **fabrics_list_tail** could - in certain scenarios - be dereferenced when it is NULL

src: Add fix to query_for_fabric

---

src/collectives.c
src/shmem_internal.h
src/shmem_team.c

This PR allows team split operations to have a stride of zero if and only if the new team size is 1.

Teams: allow split stride of zero iff size is 1

---

src/shmem_team.c

As discussed in #1122, this warning may not be necessary, especially with some upcoming proposed changes to the specification to clarify this special case.
For now this PR changes this to a debug message, so at least users will not see any message unless the env var `SHMEM_DEBUG=1` is set.
I could likely be convinced to remove this message entirely, but given the state of the OpenSHMEM v1.5 spec, which is unclear as to whether a null `config` argument is acceptable, a debug message might be a better "compromise".
@dalcinl @stewartl318 @mrogowski - I invited you as collaborators to review, you'll need to accept it in email.

Teams: move warning to debug message for config_mask==0 and config == null

---

src/shmem_team.c

Coverity says this is a high impact memory leak.

teams: free allocated team if invalid config_mask

---

src/shmem_team.c

This relates to PRs #1138 and #1122.  It removes the debug message in the case that `config_mask == 0` and `config == null`.

Teams: remove debug msg if mask==0 & config!=null

---

src/transport_ofi.c

During discussion with @davidozog , it came up that we may want to make the "Could not detect any NICs with affinity to the process" message a debug message rather than a warning.

src: Change NIC affinity warning to debug message

---

src/Makefile.am

This comes from a perfectly reasonable request from @abrooks98 to link in `pmi-simple` as a direct dependency of `libsma`, when `pmi-simple` is enabled.

configury: add -lpmi_simple to AM_LDFLAGS

---

src/shmem_team.c

PR #1153 adds a fix to `shmem_team_split_strided` to interpret the stride argument provided to the API as being relative to the parent team (i.e. consistent with OpenSHMEM spec).
The fix was implemented in `shmem_internal_team_split_strided`, which is also utilized by `shmem_internal_split_2d`. However,  `shmem_internal_team_split_2d` was already passing parent team-relative stride values to its calls to `shmem_internal_team_split_strided`, so it is now being doubly converted following the recent changes.

src: Fix bug in shmem_team_split_2d

---

src/shmem_team.c

Global stride calculations might be incorrect if user passes a stride of 0 (or a size of 1 and some non-unity stride).  This ensures nonzero internal stride values, and cleans up the sanity checks.

teams: force split stride to be nonzero + cleanup

---

NEWS
configure.ac

I will post the release and align `tests-sos` after this is merged.

Release: NEWS for v1.5.3 and version update

---

src/runtime_util.c

MAX_HOSTNAME_LEN is the maximum total characters of the hostname not including the end of string character '\0'. If the hostname happens to be 64 characters long, gethostname() would return an error and shmem_runtime_util_put_hostname() would state error "gethostname failed (-1)"
Changed length to MAX_HOSTNAME_LEN+1
Issue #1159

Fixed Off-by-one error in gethostname()

---

.github/workflows/ci.yml

Updated actions/cache@v4
Issue #1165

CI: GitHub actions/cache@v2 is deprecated

---

config/getdate.sh
config/ompi_check_ucx.m4
config/opal_case_sensitive_fs_setup.m4
config/opal_check_attributes.m4
config/opal_check_libnl.m4
config/opal_check_ofi.m4
config/opal_check_pmi.m4
config/opal_check_portals4.m4
config/opal_check_visibility.m4
config/opal_functions.m4
configure.ac

This PR aligns SOS's configury with OMPI's main branch ref [cebad71e](https://github.com/open-mpi/ompi/commit/cebad71e4f50d49e486ccd54668cf58698556a7c)
It removes several configure-time warnings about obsolete autotools features and adds relevant updates for OFI (esp. for HMEM), UCX, and Portals4.
All changes from `OMPI/config/*` are verbatim, and `SOS/configure.ac` was run through `autoupdate`.

configury: update much configury to OMPI main

---

.github/workflows/ci.yml

There two issues with UCX in CI #1148 and #1048 that are under debug. Temporarily disable the test until these tickets are root caused and resolved inorder to reduce noise in CI results.

CI: Ignore failures during UCX testing

---

configure.ac

Issue #1162
The build system relies on libtool to build libraries. libtool will insert an rpath into libraries unless you set hardcode_into_libs = no. Modified configury to set hardcode_into_libs if disable-rpath is set.

configury: Fixed disable-rpath

---

configure.ac

Configure such that the Fortran API is always disabled unless explicitly enabled.
Fortran was deprecated in OpenSHMEM v1.4 and removed in v1.5, and this seems to cause problems with updating the `sos` Spack package, at least for me.
Closes #1184

configury: disable Fortran unless --enable-fortran

---

configure.ac

This addresses issue #1194.
The solution is a little strange and derived from some poorly documented features of `libtool` that I learned about from stackoverflow - so I cite that source.
It essentially adds a dummy symbol to `hardcode_libdir_flag_spec`, which prevents flags like `-Wl,-rpath -Wl,/path/to/libfabric/lib -Wl,-rpath -Wl,/path/to/SOS/lib` from being added to the link line for the `tests-sos` binaries.

configury: -disable-rpath carried through to tests

---

README
src/shmem_env_defs.h
src/transport_ofi.c
src/transport_ofi.h

SOS currently opens 2 libfabric endpoints (EPs) per process, which can lead to Rx/TX resource exhaustion in scale-up scenarios (like with 1 process per core, when there are more cores on the CPU than there are contexts on the NIC - see https://github.com/Sandia-OpenSHMEM/SOS/issues/1127).  This PR merges those 2 endpoints, which benefits scaling (i.e., it  improves the maximum PPN by 2x in typical cases), and seems to improve overall performance due to better runtime progress.
In this PR I propose we make single-EP the default behavior for SOS over OFI transport.  The optimization can be disabled by setting the new env var `SHMEM_OFI_DISABLE_SINGLE_EP`.
This also has the benefit of enabling `FI_MANUAL_PROGRESS` for a few providers, like OPX, TCP, and sockets - when SOS is configured with …

ofi: merge the default ctx and target endpoints

---

.github/workflows/ci.yml

CI: Update to Ubuntu 24.04

---

.github/scripts/gdb_dump_info.cmd
.github/scripts/scan_core.sh
.github/workflows/ci.yml

* XPMEM build failure due to use of deprecated paging macros #1206
* pud_large() and pmd_large() are not supported in newer Linux kernels
* Stubbed out pud_large() and pmd_large() referenced in xpmem_vaddr_to_pte_offset() via CI build script
* xpmem_vaddr_to_pte_offset() not used by SOS, so tests are not impacted
* Added timeout for SOS tests
* Added core dump artifact uploading and logging support
* Updated OFI testing to version 2.1.x
* Disabled failing Portals 4 tests #1208

CI: Various Improvements to CI
